-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_hls_flash_attention_hls_Pipeline_FIND_MAX is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    k_lim : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln138 : IN STD_LOGIC_VECTOR (5 downto 0);
    scores_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    scores_ce0 : OUT STD_LOGIC;
    scores_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    tile_max_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    tile_max_out_ap_vld : OUT STD_LOGIC;
    grp_fu_948_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_948_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_948_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_948_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_948_p_ce : OUT STD_LOGIC );
end;


architecture behav of flash_attention_hls_flash_attention_hls_Pipeline_FIND_MAX is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_F149F2CA : STD_LOGIC_VECTOR (31 downto 0) := "11110001010010011111001011001010";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln136_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln136_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal tile_max_load_1_reg_261 : STD_LOGIC_VECTOR (31 downto 0);
    signal tile_max_1_reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln138_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_273 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_1_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_1_reg_278 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_2_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_2_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_3_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_3_reg_288 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln138_1_fu_128_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tile_max_fu_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal tile_max_2_fu_222_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_tile_max_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_48 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln136_fu_112_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_sig_allocacmp_j_2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln136_fu_102_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln138_fu_118_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln138_fu_122_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal bitcast_ln138_fu_142_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln138_1_fu_160_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_146_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln138_1_fu_156_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_3_fu_164_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln138_2_fu_174_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln138_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln138_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln138_1_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln138_1_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_hls_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component flash_attention_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component flash_attention_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln136_fu_106_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_48 <= add_ln136_fu_112_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_48 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;

    tile_max_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    tile_max_fu_44 <= ap_const_lv32_F149F2CA;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    tile_max_fu_44 <= tile_max_2_fu_222_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln136_reg_252 <= icmp_ln136_fu_106_p2;
                icmp_ln138_1_reg_278 <= icmp_ln138_1_fu_184_p2;
                icmp_ln138_2_reg_283 <= icmp_ln138_2_fu_190_p2;
                icmp_ln138_3_reg_288 <= icmp_ln138_3_fu_196_p2;
                icmp_ln138_reg_273 <= icmp_ln138_fu_178_p2;
                tile_max_1_reg_267 <= scores_q0;
                tile_max_load_1_reg_261 <= ap_sig_allocacmp_tile_max_load_1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln136_fu_112_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_2) + unsigned(ap_const_lv31_1));
    add_ln138_fu_122_p2 <= std_logic_vector(unsigned(zext_ln138) + unsigned(trunc_ln138_fu_118_p1));
    and_ln138_1_fu_216_p2 <= (or_ln138_1_fu_206_p2 and and_ln138_fu_210_p2);
    and_ln138_fu_210_p2 <= (or_ln138_fu_202_p2 and grp_fu_948_p_dout0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln136_fu_106_p2)
    begin
        if (((icmp_ln136_fu_106_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_fu_48)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_2 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_j_2 <= j_fu_48;
        end if; 
    end process;


    ap_sig_allocacmp_tile_max_load_1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tile_max_fu_44, tile_max_2_fu_222_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_tile_max_load_1 <= tile_max_2_fu_222_p3;
        else 
            ap_sig_allocacmp_tile_max_load_1 <= tile_max_fu_44;
        end if; 
    end process;

    bitcast_ln138_1_fu_160_p1 <= ap_sig_allocacmp_tile_max_load_1;
    bitcast_ln138_fu_142_p1 <= scores_q0;
    grp_fu_948_p_ce <= ap_const_logic_1;
    grp_fu_948_p_din0 <= scores_q0;
    grp_fu_948_p_din1 <= ap_sig_allocacmp_tile_max_load_1;
    grp_fu_948_p_opcode <= ap_const_lv5_2;
    icmp_ln136_fu_106_p2 <= "1" when (signed(zext_ln136_fu_102_p1) < signed(k_lim)) else "0";
    icmp_ln138_1_fu_184_p2 <= "1" when (trunc_ln138_1_fu_156_p1 = ap_const_lv23_0) else "0";
    icmp_ln138_2_fu_190_p2 <= "0" when (tmp_3_fu_164_p4 = ap_const_lv8_FF) else "1";
    icmp_ln138_3_fu_196_p2 <= "1" when (trunc_ln138_2_fu_174_p1 = ap_const_lv23_0) else "0";
    icmp_ln138_fu_178_p2 <= "0" when (tmp_2_fu_146_p4 = ap_const_lv8_FF) else "1";
    or_ln138_1_fu_206_p2 <= (icmp_ln138_3_reg_288 or icmp_ln138_2_reg_283);
    or_ln138_fu_202_p2 <= (icmp_ln138_reg_273 or icmp_ln138_1_reg_278);
    scores_address0 <= zext_ln138_1_fu_128_p1(6 - 1 downto 0);

    scores_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            scores_ce0 <= ap_const_logic_1;
        else 
            scores_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tile_max_2_fu_222_p3 <= 
        tile_max_1_reg_267 when (and_ln138_1_fu_216_p2(0) = '1') else 
        tile_max_load_1_reg_261;
    tile_max_out <= tile_max_fu_44;

    tile_max_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln136_reg_252)
    begin
        if (((icmp_ln136_reg_252 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_max_out_ap_vld <= ap_const_logic_1;
        else 
            tile_max_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_146_p4 <= bitcast_ln138_fu_142_p1(30 downto 23);
    tmp_3_fu_164_p4 <= bitcast_ln138_1_fu_160_p1(30 downto 23);
    trunc_ln138_1_fu_156_p1 <= bitcast_ln138_fu_142_p1(23 - 1 downto 0);
    trunc_ln138_2_fu_174_p1 <= bitcast_ln138_1_fu_160_p1(23 - 1 downto 0);
    trunc_ln138_fu_118_p1 <= ap_sig_allocacmp_j_2(6 - 1 downto 0);
    zext_ln136_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_j_2),32));
    zext_ln138_1_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln138_fu_122_p2),64));
end behav;
