-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_hls_flash_attention_hls_Pipeline_LOAD_KV_VITIS_LOOP_93_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln87 : IN STD_LOGIC_VECTOR (63 downto 0);
    Kbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Kbuf_ce0 : OUT STD_LOGIC;
    Kbuf_we0 : OUT STD_LOGIC;
    Kbuf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Kbuf_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Kbuf_1_ce0 : OUT STD_LOGIC;
    Kbuf_1_we0 : OUT STD_LOGIC;
    Kbuf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Kbuf_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Kbuf_2_ce0 : OUT STD_LOGIC;
    Kbuf_2_we0 : OUT STD_LOGIC;
    Kbuf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Kbuf_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Kbuf_3_ce0 : OUT STD_LOGIC;
    Kbuf_3_we0 : OUT STD_LOGIC;
    Kbuf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Vbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Vbuf_ce0 : OUT STD_LOGIC;
    Vbuf_we0 : OUT STD_LOGIC;
    Vbuf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Vbuf_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Vbuf_1_ce0 : OUT STD_LOGIC;
    Vbuf_1_we0 : OUT STD_LOGIC;
    Vbuf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Vbuf_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Vbuf_2_ce0 : OUT STD_LOGIC;
    Vbuf_2_we0 : OUT STD_LOGIC;
    Vbuf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Vbuf_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Vbuf_3_ce0 : OUT STD_LOGIC;
    Vbuf_3_we0 : OUT STD_LOGIC;
    Vbuf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    zext_ln63 : IN STD_LOGIC_VECTOR (30 downto 0);
    shl_ln92_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    V : IN STD_LOGIC_VECTOR (63 downto 0);
    K : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of flash_attention_hls_flash_attention_hls_Pipeline_LOAD_KV_VITIS_LOOP_93_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln92_reg_590 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_reg_590_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln92_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem2_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem2_blk_n_AR : STD_LOGIC;
    signal gmem1_blk_n_R : STD_LOGIC;
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal first_iter_1_reg_284 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln63_cast_fu_296_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_cast_reg_580 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln92_reg_586 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln92_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln92_1_fu_382_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln92_1_reg_594 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln93_fu_394_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln93_reg_599_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln95_fu_408_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln95_reg_603_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal gmem1_addr_reg_608 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem2_addr_reg_614 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem1_addr_read_reg_620 : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem2_addr_read_reg_625 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_first_iter_1_phi_fu_288_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln95_fu_509_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln93_fu_479_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln93_1_fu_499_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_3_fu_110 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln93_fu_414_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal j_fu_114 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln92_1_fu_370_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten9_fu_118 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln92_4_fu_335_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln95_fu_520_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln96_fu_527_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln93_fu_321_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln93_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln92_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln92_3_fu_344_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln92_fu_378_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln92_fu_362_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_s_fu_386_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln3_fu_398_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln92_2_fu_435_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln92_fu_442_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1_fu_447_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln92_fu_455_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln92_2_fu_464_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln5_fu_469_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln92_1_fu_459_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln93_1_fu_489_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component flash_attention_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_1_reg_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln92_reg_586 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_1_reg_284 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_1_reg_284 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    indvar_flatten9_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten9_fu_118 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln92_fu_330_p2 = ap_const_lv1_0))) then 
                    indvar_flatten9_fu_118 <= add_ln92_4_fu_335_p2;
                end if;
            end if; 
        end if;
    end process;

    j_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_114 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln92_fu_330_p2 = ap_const_lv1_0))) then 
                    j_fu_114 <= select_ln92_1_fu_370_p3;
                end if;
            end if; 
        end if;
    end process;

    x_3_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_3_fu_110 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln92_fu_330_p2 = ap_const_lv1_0))) then 
                    x_3_fu_110 <= add_ln93_fu_414_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln95_reg_603 <= add_ln95_fu_408_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln92_reg_586 <= icmp_ln92_fu_330_p2;
                or_ln92_reg_590 <= or_ln92_fu_356_p2;
                trunc_ln92_1_reg_594 <= trunc_ln92_1_fu_382_p1;
                trunc_ln93_reg_599 <= trunc_ln93_fu_394_p1;
                    zext_ln63_cast_reg_580(30 downto 0) <= zext_ln63_cast_fu_296_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln95_reg_603_pp0_iter10_reg <= add_ln95_reg_603_pp0_iter9_reg;
                add_ln95_reg_603_pp0_iter11_reg <= add_ln95_reg_603_pp0_iter10_reg;
                add_ln95_reg_603_pp0_iter2_reg <= add_ln95_reg_603;
                add_ln95_reg_603_pp0_iter3_reg <= add_ln95_reg_603_pp0_iter2_reg;
                add_ln95_reg_603_pp0_iter4_reg <= add_ln95_reg_603_pp0_iter3_reg;
                add_ln95_reg_603_pp0_iter5_reg <= add_ln95_reg_603_pp0_iter4_reg;
                add_ln95_reg_603_pp0_iter6_reg <= add_ln95_reg_603_pp0_iter5_reg;
                add_ln95_reg_603_pp0_iter7_reg <= add_ln95_reg_603_pp0_iter6_reg;
                add_ln95_reg_603_pp0_iter8_reg <= add_ln95_reg_603_pp0_iter7_reg;
                add_ln95_reg_603_pp0_iter9_reg <= add_ln95_reg_603_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem1_addr_read_reg_620 <= m_axi_gmem1_RDATA;
                gmem1_addr_reg_608 <= sext_ln93_fu_479_p1;
                gmem2_addr_read_reg_625 <= m_axi_gmem2_RDATA;
                gmem2_addr_reg_614 <= sext_ln93_1_fu_499_p1;
                or_ln92_reg_590_pp0_iter2_reg <= or_ln92_reg_590;
                trunc_ln93_reg_599_pp0_iter10_reg <= trunc_ln93_reg_599_pp0_iter9_reg;
                trunc_ln93_reg_599_pp0_iter11_reg <= trunc_ln93_reg_599_pp0_iter10_reg;
                trunc_ln93_reg_599_pp0_iter2_reg <= trunc_ln93_reg_599;
                trunc_ln93_reg_599_pp0_iter3_reg <= trunc_ln93_reg_599_pp0_iter2_reg;
                trunc_ln93_reg_599_pp0_iter4_reg <= trunc_ln93_reg_599_pp0_iter3_reg;
                trunc_ln93_reg_599_pp0_iter5_reg <= trunc_ln93_reg_599_pp0_iter4_reg;
                trunc_ln93_reg_599_pp0_iter6_reg <= trunc_ln93_reg_599_pp0_iter5_reg;
                trunc_ln93_reg_599_pp0_iter7_reg <= trunc_ln93_reg_599_pp0_iter6_reg;
                trunc_ln93_reg_599_pp0_iter8_reg <= trunc_ln93_reg_599_pp0_iter7_reg;
                trunc_ln93_reg_599_pp0_iter9_reg <= trunc_ln93_reg_599_pp0_iter8_reg;
            end if;
        end if;
    end process;
    zext_ln63_cast_reg_580(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Kbuf_1_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Kbuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_1_ce0 <= ap_const_logic_1;
        else 
            Kbuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_1_d0 <= bitcast_ln95_fu_520_p1;

    Kbuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_1_we0 <= ap_const_logic_1;
        else 
            Kbuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_2_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Kbuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_2_ce0 <= ap_const_logic_1;
        else 
            Kbuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_2_d0 <= bitcast_ln95_fu_520_p1;

    Kbuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_2_we0 <= ap_const_logic_1;
        else 
            Kbuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_3_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Kbuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_3_ce0 <= ap_const_logic_1;
        else 
            Kbuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_3_d0 <= bitcast_ln95_fu_520_p1;

    Kbuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_3_we0 <= ap_const_logic_1;
        else 
            Kbuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Kbuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_ce0 <= ap_const_logic_1;
        else 
            Kbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Kbuf_d0 <= bitcast_ln95_fu_520_p1;

    Kbuf_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Kbuf_we0 <= ap_const_logic_1;
        else 
            Kbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_1_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Vbuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_1_ce0 <= ap_const_logic_1;
        else 
            Vbuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_1_d0 <= bitcast_ln96_fu_527_p1;

    Vbuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_1_we0 <= ap_const_logic_1;
        else 
            Vbuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_2_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Vbuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_2_ce0 <= ap_const_logic_1;
        else 
            Vbuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_2_d0 <= bitcast_ln96_fu_527_p1;

    Vbuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_2_we0 <= ap_const_logic_1;
        else 
            Vbuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_3_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Vbuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_3_ce0 <= ap_const_logic_1;
        else 
            Vbuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_3_d0 <= bitcast_ln96_fu_527_p1;

    Vbuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_3_we0 <= ap_const_logic_1;
        else 
            Vbuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_address0 <= zext_ln95_fu_509_p1(6 - 1 downto 0);

    Vbuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_ce0 <= ap_const_logic_1;
        else 
            Vbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Vbuf_d0 <= bitcast_ln96_fu_527_p1;

    Vbuf_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln93_reg_599_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln93_reg_599_pp0_iter11_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Vbuf_we0 <= ap_const_logic_1;
        else 
            Vbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln92_1_fu_459_p2 <= std_logic_vector(signed(sext_ln92_fu_455_p1) + signed(V));
    add_ln92_2_fu_464_p2 <= std_logic_vector(signed(sext_ln92_fu_455_p1) + signed(K));
    add_ln92_3_fu_344_p2 <= std_logic_vector(unsigned(j_fu_114) + unsigned(ap_const_lv31_1));
    add_ln92_4_fu_335_p2 <= std_logic_vector(unsigned(indvar_flatten9_fu_118) + unsigned(ap_const_lv64_1));
    add_ln92_fu_442_p2 <= std_logic_vector(unsigned(shl_ln92_2_fu_435_p3) + unsigned(shl_ln92_1));
    add_ln93_fu_414_p2 <= std_logic_vector(unsigned(select_ln92_fu_362_p3) + unsigned(ap_const_lv31_1));
    add_ln95_fu_408_p2 <= std_logic_vector(unsigned(tmp_s_fu_386_p3) + unsigned(lshr_ln3_fu_398_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, ap_block_state4_io, ap_block_state12_pp0_stage0_iter11)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage0_iter11)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, ap_block_state4_io, ap_block_state12_pp0_stage0_iter11)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage0_iter11)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_state12_pp0_stage0_iter11_assign_proc : process(m_axi_gmem1_RVALID, m_axi_gmem2_RVALID)
    begin
                ap_block_state12_pp0_stage0_iter11 <= ((m_axi_gmem2_RVALID = ap_const_logic_0) or (m_axi_gmem1_RVALID = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem1_ARREADY, m_axi_gmem2_ARREADY, or_ln92_reg_590_pp0_iter2_reg)
    begin
                ap_block_state4_io <= (((or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1) and (m_axi_gmem2_ARREADY = ap_const_logic_0)) or ((m_axi_gmem1_ARREADY = ap_const_logic_0) and (or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1)));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln92_fu_330_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln92_fu_330_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_1_phi_fu_288_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, first_iter_1_reg_284, icmp_ln92_reg_586)
    begin
        if (((icmp_ln92_reg_586 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_1_phi_fu_288_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_1_phi_fu_288_p4 <= first_iter_1_reg_284;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln95_fu_520_p1 <= gmem1_addr_read_reg_620;
    bitcast_ln96_fu_527_p1 <= gmem2_addr_read_reg_625;

    gmem1_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem1_ARREADY, or_ln92_reg_590_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1))) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem1_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem1_blk_n_R <= m_axi_gmem1_RVALID;
        else 
            gmem1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem2_ARREADY, or_ln92_reg_590_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1))) then 
            gmem2_blk_n_AR <= m_axi_gmem2_ARREADY;
        else 
            gmem2_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem2_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem2_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem2_blk_n_R <= m_axi_gmem2_RVALID;
        else 
            gmem2_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln92_fu_330_p2 <= "1" when (indvar_flatten9_fu_118 = mul_ln87) else "0";
    icmp_ln93_fu_325_p2 <= "1" when (signed(zext_ln93_fu_321_p1) < signed(d)) else "0";
    lshr_ln3_fu_398_p4 <= select_ln92_fu_362_p3(7 downto 2);
    m_axi_gmem1_ARADDR <= gmem1_addr_reg_608;
    m_axi_gmem1_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_ARID <= ap_const_lv1_0;
    m_axi_gmem1_ARLEN <= zext_ln63_cast_reg_580;
    m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_ARUSER <= ap_const_lv1_0;

    m_axi_gmem1_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter3, or_ln92_reg_590_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem1_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    m_axi_gmem2_ARADDR <= gmem2_addr_reg_614;
    m_axi_gmem2_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_ARID <= ap_const_lv1_0;
    m_axi_gmem2_ARLEN <= zext_ln63_cast_reg_580;
    m_axi_gmem2_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_ARUSER <= ap_const_lv1_0;

    m_axi_gmem2_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter3, or_ln92_reg_590_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln92_reg_590_pp0_iter2_reg = ap_const_lv1_1))) then 
            m_axi_gmem2_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem2_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_AWADDR <= ap_const_lv64_0;
    m_axi_gmem2_AWBURST <= ap_const_lv2_0;
    m_axi_gmem2_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem2_AWID <= ap_const_lv1_0;
    m_axi_gmem2_AWLEN <= ap_const_lv32_0;
    m_axi_gmem2_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem2_AWPROT <= ap_const_lv3_0;
    m_axi_gmem2_AWQOS <= ap_const_lv4_0;
    m_axi_gmem2_AWREGION <= ap_const_lv4_0;
    m_axi_gmem2_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem2_AWUSER <= ap_const_lv1_0;
    m_axi_gmem2_AWVALID <= ap_const_logic_0;
    m_axi_gmem2_BREADY <= ap_const_logic_0;

    m_axi_gmem2_RREADY_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem2_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem2_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_WDATA <= ap_const_lv32_0;
    m_axi_gmem2_WID <= ap_const_lv1_0;
    m_axi_gmem2_WLAST <= ap_const_logic_0;
    m_axi_gmem2_WSTRB <= ap_const_lv4_0;
    m_axi_gmem2_WUSER <= ap_const_lv1_0;
    m_axi_gmem2_WVALID <= ap_const_logic_0;
    or_ln92_fu_356_p2 <= (xor_ln92_fu_350_p2 or ap_phi_mux_first_iter_1_phi_fu_288_p4);
    select_ln92_1_fu_370_p3 <= 
        j_fu_114 when (icmp_ln93_fu_325_p2(0) = '1') else 
        add_ln92_3_fu_344_p2;
    select_ln92_fu_362_p3 <= 
        x_3_fu_110 when (icmp_ln93_fu_325_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln92_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1_fu_447_p3),64));

        sext_ln93_1_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln93_1_fu_489_p4),64));

        sext_ln93_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln5_fu_469_p4),64));

    shl_ln1_fu_447_p3 <= (add_ln92_fu_442_p2 & ap_const_lv2_0);
    shl_ln92_2_fu_435_p3 <= (trunc_ln92_1_reg_594 & ap_const_lv5_0);
    tmp_s_fu_386_p3 <= (trunc_ln92_fu_378_p1 & ap_const_lv3_0);
    trunc_ln5_fu_469_p4 <= add_ln92_2_fu_464_p2(63 downto 2);
    trunc_ln92_1_fu_382_p1 <= select_ln92_1_fu_370_p3(27 - 1 downto 0);
    trunc_ln92_fu_378_p1 <= select_ln92_1_fu_370_p3(3 - 1 downto 0);
    trunc_ln93_1_fu_489_p4 <= add_ln92_1_fu_459_p2(63 downto 2);
    trunc_ln93_fu_394_p1 <= select_ln92_fu_362_p3(2 - 1 downto 0);
    xor_ln92_fu_350_p2 <= (icmp_ln93_fu_325_p2 xor ap_const_lv1_1);
    zext_ln63_cast_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln63),32));
    zext_ln93_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_3_fu_110),32));
    zext_ln95_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_reg_603_pp0_iter11_reg),64));
end behav;
