// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_STORE_O_VITIS_LOOP_188_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        d,
        mul_ln187,
        acc_address0,
        acc_ce0,
        acc_q0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_q0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_q0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_q0,
        zext_ln63,
        shl_ln68_2,
        O
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [31:0] m_axi_gmem3_WDATA;
output  [3:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [31:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [31:0] d;
input  [63:0] mul_ln187;
output  [5:0] acc_address0;
output   acc_ce0;
input  [31:0] acc_q0;
output  [5:0] acc_1_address0;
output   acc_1_ce0;
input  [31:0] acc_1_q0;
output  [5:0] acc_2_address0;
output   acc_2_ce0;
input  [31:0] acc_2_q0;
output  [5:0] acc_3_address0;
output   acc_3_ce0;
input  [31:0] acc_3_q0;
input  [30:0] zext_ln63;
input  [31:0] shl_ln68_2;
input  [63:0] O;

reg ap_idle;
reg m_axi_gmem3_AWVALID;
reg m_axi_gmem3_WVALID;
reg m_axi_gmem3_BREADY;
reg acc_ce0;
reg acc_1_ce0;
reg acc_2_ce0;
reg acc_3_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] or_ln187_reg_522;
reg   [0:0] or_ln187_reg_522_pp0_iter2_reg;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln188_1_reg_571;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter8_reg;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln187_fu_269_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem3_blk_n_B;
wire    ap_block_pp0_stage0;
reg    gmem3_blk_n_W;
reg    gmem3_blk_n_AW;
reg   [0:0] first_iter_3_reg_223;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln63_cast_fu_235_p1;
reg   [31:0] zext_ln63_cast_reg_513;
reg   [0:0] icmp_ln187_reg_518;
wire   [0:0] or_ln187_fu_295_p2;
wire   [3:0] select_ln187_1_fu_309_p3;
reg   [3:0] select_ln187_1_reg_526;
wire   [1:0] trunc_ln188_fu_329_p1;
reg   [1:0] trunc_ln188_reg_531;
reg   [1:0] trunc_ln188_reg_531_pp0_iter2_reg;
wire   [5:0] add_ln190_fu_343_p2;
reg   [5:0] add_ln190_reg_536;
wire   [30:0] add_ln188_fu_349_p2;
reg   [30:0] add_ln188_reg_541;
reg   [61:0] sext_ln188_mid2_v_reg_546;
wire   [0:0] icmp_ln188_1_fu_423_p2;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter3_reg;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter4_reg;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter5_reg;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter6_reg;
reg   [0:0] icmp_ln188_1_reg_571_pp0_iter7_reg;
wire   [31:0] tmp_1_fu_438_p11;
reg   [31:0] tmp_1_reg_575;
reg   [0:0] ap_phi_mux_first_iter_3_phi_fu_227_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln190_fu_413_p1;
wire  signed [63:0] sext_ln187_1_fu_428_p1;
reg    ap_block_pp0_stage0_01001;
reg   [30:0] x_2_fu_110;
reg   [3:0] i_fu_114;
reg   [63:0] indvar_flatten44_fu_118;
wire   [63:0] add_ln187_3_fu_274_p2;
wire   [31:0] zext_ln188_fu_260_p1;
wire   [0:0] icmp_ln188_fu_264_p2;
wire   [0:0] xor_ln187_fu_289_p2;
wire   [3:0] add_ln187_fu_283_p2;
wire   [2:0] trunc_ln187_fu_317_p1;
wire   [30:0] select_ln187_fu_301_p3;
wire   [5:0] tmp_s_fu_321_p3;
wire   [5:0] lshr_ln2_fu_333_p4;
wire   [8:0] sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3;
wire   [31:0] zext_ln187_fu_377_p1;
wire   [31:0] add_ln187_1_fu_381_p2;
wire   [33:0] sext_ln188_mid2_v_v_v_v_v_fu_386_p3;
wire  signed [63:0] sext_ln187_fu_394_p1;
wire   [63:0] add_ln187_2_fu_398_p2;
wire   [31:0] zext_ln188_1_fu_420_p1;
wire   [31:0] tmp_1_fu_438_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [1:0] tmp_1_fu_438_p1;
wire   [1:0] tmp_1_fu_438_p3;
wire  signed [1:0] tmp_1_fu_438_p5;
wire  signed [1:0] tmp_1_fu_438_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 x_2_fu_110 = 31'd0;
#0 i_fu_114 = 4'd0;
#0 indvar_flatten44_fu_118 = 64'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U196(
    .din0(acc_q0),
    .din1(acc_1_q0),
    .din2(acc_2_q0),
    .din3(acc_3_q0),
    .def(tmp_1_fu_438_p9),
    .sel(trunc_ln188_reg_531_pp0_iter2_reg),
    .dout(tmp_1_fu_438_p11)
);

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln187_reg_518 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_3_reg_223 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_3_reg_223 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_114 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln187_fu_269_p2 == 1'd0))) begin
            i_fu_114 <= select_ln187_1_fu_309_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten44_fu_118 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln187_fu_269_p2 == 1'd0))) begin
            indvar_flatten44_fu_118 <= add_ln187_3_fu_274_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_2_fu_110 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln187_fu_269_p2 == 1'd0))) begin
            x_2_fu_110 <= add_ln188_fu_349_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln188_reg_541 <= add_ln188_fu_349_p2;
        add_ln190_reg_536 <= add_ln190_fu_343_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln187_reg_518 <= icmp_ln187_fu_269_p2;
        or_ln187_reg_522 <= or_ln187_fu_295_p2;
        select_ln187_1_reg_526 <= select_ln187_1_fu_309_p3;
        trunc_ln188_reg_531 <= trunc_ln188_fu_329_p1;
        zext_ln63_cast_reg_513[30 : 0] <= zext_ln63_cast_fu_235_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        icmp_ln188_1_reg_571 <= icmp_ln188_1_fu_423_p2;
        icmp_ln188_1_reg_571_pp0_iter3_reg <= icmp_ln188_1_reg_571;
        icmp_ln188_1_reg_571_pp0_iter4_reg <= icmp_ln188_1_reg_571_pp0_iter3_reg;
        icmp_ln188_1_reg_571_pp0_iter5_reg <= icmp_ln188_1_reg_571_pp0_iter4_reg;
        icmp_ln188_1_reg_571_pp0_iter6_reg <= icmp_ln188_1_reg_571_pp0_iter5_reg;
        icmp_ln188_1_reg_571_pp0_iter7_reg <= icmp_ln188_1_reg_571_pp0_iter6_reg;
        icmp_ln188_1_reg_571_pp0_iter8_reg <= icmp_ln188_1_reg_571_pp0_iter7_reg;
        or_ln187_reg_522_pp0_iter2_reg <= or_ln187_reg_522;
        sext_ln188_mid2_v_reg_546 <= {{add_ln187_2_fu_398_p2[63:2]}};
        tmp_1_reg_575 <= tmp_1_fu_438_p11;
        trunc_ln188_reg_531_pp0_iter2_reg <= trunc_ln188_reg_531;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_ce0 = 1'b1;
    end else begin
        acc_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_2_ce0 = 1'b1;
    end else begin
        acc_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_3_ce0 = 1'b1;
    end else begin
        acc_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_ce0 = 1'b1;
    end else begin
        acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln187_fu_269_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln187_reg_518 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_3_phi_fu_227_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_3_phi_fu_227_p4 = first_iter_3_reg_223;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln187_reg_522_pp0_iter2_reg == 1'd1))) begin
        gmem3_blk_n_AW = m_axi_gmem3_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln188_1_reg_571_pp0_iter8_reg == 1'd0))) begin
        gmem3_blk_n_B = m_axi_gmem3_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem3_blk_n_W = m_axi_gmem3_WREADY;
    end else begin
        gmem3_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln187_reg_522_pp0_iter2_reg == 1'd1))) begin
        m_axi_gmem3_AWVALID = 1'b1;
    end else begin
        m_axi_gmem3_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln188_1_reg_571_pp0_iter8_reg == 1'd0))) begin
        m_axi_gmem3_BREADY = 1'b1;
    end else begin
        m_axi_gmem3_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem3_WVALID = 1'b1;
    end else begin
        m_axi_gmem3_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_address0 = zext_ln190_fu_413_p1;

assign acc_2_address0 = zext_ln190_fu_413_p1;

assign acc_3_address0 = zext_ln190_fu_413_p1;

assign acc_address0 = zext_ln190_fu_413_p1;

assign add_ln187_1_fu_381_p2 = (zext_ln187_fu_377_p1 + shl_ln68_2);

assign add_ln187_2_fu_398_p2 = ($signed(sext_ln187_fu_394_p1) + $signed(O));

assign add_ln187_3_fu_274_p2 = (indvar_flatten44_fu_118 + 64'd1);

assign add_ln187_fu_283_p2 = (i_fu_114 + 4'd1);

assign add_ln188_fu_349_p2 = (select_ln187_fu_301_p3 + 31'd1);

assign add_ln190_fu_343_p2 = (tmp_s_fu_321_p3 + lshr_ln2_fu_333_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((m_axi_gmem3_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((m_axi_gmem3_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((icmp_ln188_1_reg_571_pp0_iter8_reg == 1'd0) & (m_axi_gmem3_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem3_AWREADY == 1'b0) & (or_ln187_reg_522_pp0_iter2_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign icmp_ln187_fu_269_p2 = ((indvar_flatten44_fu_118 == mul_ln187) ? 1'b1 : 1'b0);

assign icmp_ln188_1_fu_423_p2 = (($signed(zext_ln188_1_fu_420_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln188_fu_264_p2 = (($signed(zext_ln188_fu_260_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign lshr_ln2_fu_333_p4 = {{select_ln187_fu_301_p3[7:2]}};

assign m_axi_gmem3_ARADDR = 64'd0;

assign m_axi_gmem3_ARBURST = 2'd0;

assign m_axi_gmem3_ARCACHE = 4'd0;

assign m_axi_gmem3_ARID = 1'd0;

assign m_axi_gmem3_ARLEN = 32'd0;

assign m_axi_gmem3_ARLOCK = 2'd0;

assign m_axi_gmem3_ARPROT = 3'd0;

assign m_axi_gmem3_ARQOS = 4'd0;

assign m_axi_gmem3_ARREGION = 4'd0;

assign m_axi_gmem3_ARSIZE = 3'd0;

assign m_axi_gmem3_ARUSER = 1'd0;

assign m_axi_gmem3_ARVALID = 1'b0;

assign m_axi_gmem3_AWADDR = sext_ln187_1_fu_428_p1;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = zext_ln63_cast_reg_513;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_RREADY = 1'b0;

assign m_axi_gmem3_WDATA = tmp_1_reg_575;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 4'd15;

assign m_axi_gmem3_WUSER = 1'd0;

assign or_ln187_fu_295_p2 = (xor_ln187_fu_289_p2 | ap_phi_mux_first_iter_3_phi_fu_227_p4);

assign select_ln187_1_fu_309_p3 = ((icmp_ln188_fu_264_p2[0:0] == 1'b1) ? i_fu_114 : add_ln187_fu_283_p2);

assign select_ln187_fu_301_p3 = ((icmp_ln188_fu_264_p2[0:0] == 1'b1) ? x_2_fu_110 : 31'd0);

assign sext_ln187_1_fu_428_p1 = $signed(sext_ln188_mid2_v_reg_546);

assign sext_ln187_fu_394_p1 = $signed(sext_ln188_mid2_v_v_v_v_v_fu_386_p3);

assign sext_ln188_mid2_v_v_v_v_v_fu_386_p3 = {{add_ln187_1_fu_381_p2}, {2'd0}};

assign sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3 = {{select_ln187_1_reg_526}, {5'd0}};

assign tmp_1_fu_438_p9 = 'bx;

assign tmp_s_fu_321_p3 = {{trunc_ln187_fu_317_p1}, {3'd0}};

assign trunc_ln187_fu_317_p1 = select_ln187_1_fu_309_p3[2:0];

assign trunc_ln188_fu_329_p1 = select_ln187_fu_301_p3[1:0];

assign xor_ln187_fu_289_p2 = (icmp_ln188_fu_264_p2 ^ 1'd1);

assign zext_ln187_fu_377_p1 = sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3;

assign zext_ln188_1_fu_420_p1 = add_ln188_reg_541;

assign zext_ln188_fu_260_p1 = x_2_fu_110;

assign zext_ln190_fu_413_p1 = add_ln190_reg_536;

assign zext_ln63_cast_fu_235_p1 = zext_ln63;

always @ (posedge ap_clk) begin
    zext_ln63_cast_reg_513[31] <= 1'b0;
end

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_STORE_O_VITIS_LOOP_188_5
