// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_UPDATE_ACC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d,
        i_4,
        acc_address0,
        acc_ce0,
        acc_we0,
        acc_d0,
        acc_address1,
        acc_ce1,
        acc_q1,
        acc_1_address0,
        acc_1_ce0,
        acc_1_we0,
        acc_1_d0,
        acc_1_address1,
        acc_1_ce1,
        acc_1_q1,
        acc_2_address0,
        acc_2_ce0,
        acc_2_we0,
        acc_2_d0,
        acc_2_address1,
        acc_2_ce1,
        acc_2_q1,
        acc_3_address0,
        acc_3_ce0,
        acc_3_we0,
        acc_3_d0,
        acc_3_address1,
        acc_3_ce1,
        acc_3_q1,
        mul1,
        weighted_address0,
        weighted_ce0,
        weighted_q0,
        l_new,
        weighted_1_address0,
        weighted_1_ce0,
        weighted_1_q0,
        weighted_2_address0,
        weighted_2_ce0,
        weighted_2_q0,
        weighted_3_address0,
        weighted_3_ce0,
        weighted_3_q0,
        grp_fu_2294_p_din0,
        grp_fu_2294_p_din1,
        grp_fu_2294_p_opcode,
        grp_fu_2294_p_dout0,
        grp_fu_2294_p_ce,
        grp_fu_2298_p_din0,
        grp_fu_2298_p_din1,
        grp_fu_2298_p_opcode,
        grp_fu_2298_p_dout0,
        grp_fu_2298_p_ce,
        grp_fu_2302_p_din0,
        grp_fu_2302_p_din1,
        grp_fu_2302_p_opcode,
        grp_fu_2302_p_dout0,
        grp_fu_2302_p_ce,
        grp_fu_2306_p_din0,
        grp_fu_2306_p_din1,
        grp_fu_2306_p_opcode,
        grp_fu_2306_p_dout0,
        grp_fu_2306_p_ce,
        grp_fu_936_p_din0,
        grp_fu_936_p_din1,
        grp_fu_936_p_dout0,
        grp_fu_936_p_ce,
        grp_fu_2310_p_din0,
        grp_fu_2310_p_din1,
        grp_fu_2310_p_dout0,
        grp_fu_2310_p_ce,
        grp_fu_2314_p_din0,
        grp_fu_2314_p_din1,
        grp_fu_2314_p_dout0,
        grp_fu_2314_p_ce,
        grp_fu_2318_p_din0,
        grp_fu_2318_p_din1,
        grp_fu_2318_p_dout0,
        grp_fu_2318_p_ce,
        grp_fu_940_p_din0,
        grp_fu_940_p_din1,
        grp_fu_940_p_dout0,
        grp_fu_940_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] d;
input  [2:0] i_4;
output  [5:0] acc_address0;
output   acc_ce0;
output   acc_we0;
output  [31:0] acc_d0;
output  [5:0] acc_address1;
output   acc_ce1;
input  [31:0] acc_q1;
output  [5:0] acc_1_address0;
output   acc_1_ce0;
output   acc_1_we0;
output  [31:0] acc_1_d0;
output  [5:0] acc_1_address1;
output   acc_1_ce1;
input  [31:0] acc_1_q1;
output  [5:0] acc_2_address0;
output   acc_2_ce0;
output   acc_2_we0;
output  [31:0] acc_2_d0;
output  [5:0] acc_2_address1;
output   acc_2_ce1;
input  [31:0] acc_2_q1;
output  [5:0] acc_3_address0;
output   acc_3_ce0;
output   acc_3_we0;
output  [31:0] acc_3_d0;
output  [5:0] acc_3_address1;
output   acc_3_ce1;
input  [31:0] acc_3_q1;
input  [31:0] mul1;
output  [2:0] weighted_address0;
output   weighted_ce0;
input  [31:0] weighted_q0;
input  [31:0] l_new;
output  [2:0] weighted_1_address0;
output   weighted_1_ce0;
input  [31:0] weighted_1_q0;
output  [2:0] weighted_2_address0;
output   weighted_2_ce0;
input  [31:0] weighted_2_q0;
output  [2:0] weighted_3_address0;
output   weighted_3_ce0;
input  [31:0] weighted_3_q0;
output  [31:0] grp_fu_2294_p_din0;
output  [31:0] grp_fu_2294_p_din1;
output  [1:0] grp_fu_2294_p_opcode;
input  [31:0] grp_fu_2294_p_dout0;
output   grp_fu_2294_p_ce;
output  [31:0] grp_fu_2298_p_din0;
output  [31:0] grp_fu_2298_p_din1;
output  [1:0] grp_fu_2298_p_opcode;
input  [31:0] grp_fu_2298_p_dout0;
output   grp_fu_2298_p_ce;
output  [31:0] grp_fu_2302_p_din0;
output  [31:0] grp_fu_2302_p_din1;
output  [1:0] grp_fu_2302_p_opcode;
input  [31:0] grp_fu_2302_p_dout0;
output   grp_fu_2302_p_ce;
output  [31:0] grp_fu_2306_p_din0;
output  [31:0] grp_fu_2306_p_din1;
output  [1:0] grp_fu_2306_p_opcode;
input  [31:0] grp_fu_2306_p_dout0;
output   grp_fu_2306_p_ce;
output  [31:0] grp_fu_936_p_din0;
output  [31:0] grp_fu_936_p_din1;
input  [31:0] grp_fu_936_p_dout0;
output   grp_fu_936_p_ce;
output  [31:0] grp_fu_2310_p_din0;
output  [31:0] grp_fu_2310_p_din1;
input  [31:0] grp_fu_2310_p_dout0;
output   grp_fu_2310_p_ce;
output  [31:0] grp_fu_2314_p_din0;
output  [31:0] grp_fu_2314_p_din1;
input  [31:0] grp_fu_2314_p_dout0;
output   grp_fu_2314_p_ce;
output  [31:0] grp_fu_2318_p_din0;
output  [31:0] grp_fu_2318_p_din1;
input  [31:0] grp_fu_2318_p_dout0;
output   grp_fu_2318_p_ce;
output  [31:0] grp_fu_940_p_din0;
output  [31:0] grp_fu_940_p_din1;
input  [31:0] grp_fu_940_p_dout0;
output   grp_fu_940_p_ce;

reg ap_idle;
reg acc_ce0;
reg acc_we0;
reg acc_ce1;
reg acc_1_ce0;
reg acc_1_we0;
reg acc_1_ce1;
reg acc_2_ce0;
reg acc_2_we0;
reg acc_2_ce1;
reg acc_3_ce0;
reg acc_3_we0;
reg acc_3_ce1;
reg weighted_ce0;
reg weighted_1_ce0;
reg weighted_2_ce0;
reg weighted_3_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_276_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] lshr_ln5_fu_302_p4;
reg   [2:0] lshr_ln5_reg_417;
reg   [2:0] lshr_ln5_reg_417_pp0_iter1_reg;
reg   [2:0] lshr_ln5_reg_417_pp0_iter2_reg;
reg   [2:0] lshr_ln5_reg_417_pp0_iter3_reg;
reg   [5:0] acc_addr_reg_422;
reg   [5:0] acc_addr_reg_422_pp0_iter1_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter2_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter3_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter4_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter5_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter6_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter7_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter8_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter9_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter10_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter11_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter12_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter13_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter14_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter15_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter16_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter17_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter18_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter19_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter20_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter21_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter22_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter23_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter24_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter25_reg;
reg   [5:0] acc_addr_reg_422_pp0_iter26_reg;
reg   [5:0] acc_1_addr_reg_428;
reg   [5:0] acc_1_addr_reg_428_pp0_iter1_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter2_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter3_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter4_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter5_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter6_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter7_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter8_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter9_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter10_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter11_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter12_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter13_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter14_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter15_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter16_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter17_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter18_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter19_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter20_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter21_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter22_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter23_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter24_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter25_reg;
reg   [5:0] acc_1_addr_reg_428_pp0_iter26_reg;
reg   [5:0] acc_2_addr_reg_434;
reg   [5:0] acc_2_addr_reg_434_pp0_iter1_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter2_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter3_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter4_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter5_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter6_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter7_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter8_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter9_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter10_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter11_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter12_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter13_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter14_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter15_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter16_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter17_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter18_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter19_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter20_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter21_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter22_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter23_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter24_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter25_reg;
reg   [5:0] acc_2_addr_reg_434_pp0_iter26_reg;
reg   [5:0] acc_3_addr_reg_440;
reg   [5:0] acc_3_addr_reg_440_pp0_iter1_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter2_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter3_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter4_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter5_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter6_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter7_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter8_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter9_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter10_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter11_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter12_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter13_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter14_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter15_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter16_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter17_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter18_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter19_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter20_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter21_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter22_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter23_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter24_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter25_reg;
reg   [5:0] acc_3_addr_reg_440_pp0_iter26_reg;
wire   [0:0] icmp_ln174_fu_328_p2;
reg   [0:0] icmp_ln174_reg_446;
reg   [0:0] icmp_ln174_reg_446_pp0_iter1_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter2_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter3_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter4_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter5_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter6_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter7_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter8_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter9_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter10_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter11_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter12_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter13_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter14_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter15_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter16_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter17_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter18_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter19_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter20_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter21_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter22_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter23_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter24_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter25_reg;
reg   [0:0] icmp_ln174_reg_446_pp0_iter26_reg;
wire   [0:0] icmp_ln174_1_fu_334_p2;
reg   [0:0] icmp_ln174_1_reg_450;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter1_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter2_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter3_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter4_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter5_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter6_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter7_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter8_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter9_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter10_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter11_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter12_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter13_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter14_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter15_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter16_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter17_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter18_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter19_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter20_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter21_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter22_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter23_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter24_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter25_reg;
reg   [0:0] icmp_ln174_1_reg_450_pp0_iter26_reg;
wire   [0:0] icmp_ln174_2_fu_350_p2;
reg   [0:0] icmp_ln174_2_reg_454;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter1_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter2_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter3_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter4_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter5_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter6_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter7_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter8_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter9_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter10_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter11_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter12_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter13_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter14_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter15_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter16_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter17_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter18_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter19_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter20_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter21_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter22_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter23_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter24_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter25_reg;
reg   [0:0] icmp_ln174_2_reg_454_pp0_iter26_reg;
wire   [0:0] icmp_ln174_3_fu_366_p2;
reg   [0:0] icmp_ln174_3_reg_458;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter1_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter2_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter3_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter4_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter5_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter6_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter7_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter8_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter9_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter10_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter11_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter12_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter13_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter14_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter15_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter16_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter17_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter18_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter19_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter20_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter21_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter22_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter23_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter24_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter25_reg;
reg   [0:0] icmp_ln174_3_reg_458_pp0_iter26_reg;
reg   [31:0] acc_load_reg_462;
reg   [31:0] acc_1_load_reg_467;
reg   [31:0] acc_2_load_reg_472;
reg   [31:0] acc_3_load_reg_477;
reg   [31:0] mul3_reg_502;
reg   [31:0] weighted_load_reg_507;
reg   [31:0] mul231_1_reg_512;
reg   [31:0] weighted_1_load_reg_517;
reg   [31:0] mul231_2_reg_522;
reg   [31:0] weighted_2_load_reg_527;
reg   [31:0] mul231_3_reg_532;
reg   [31:0] weighted_3_load_reg_537;
reg   [31:0] add1_reg_542;
reg   [31:0] add234_1_reg_547;
reg   [31:0] add234_2_reg_552;
reg   [31:0] add234_3_reg_557;
reg   [31:0] div_reg_562;
wire   [31:0] grp_fu_256_p2;
reg   [31:0] div235_1_reg_567;
wire   [31:0] grp_fu_260_p2;
reg   [31:0] div235_2_reg_572;
wire   [31:0] grp_fu_264_p2;
reg   [31:0] div235_3_reg_577;
wire   [63:0] zext_ln176_fu_320_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln172_2_fu_383_p1;
reg   [5:0] x_fu_72;
wire   [5:0] add_ln172_fu_372_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_x_3;
wire   [4:0] trunc_ln172_fu_284_p1;
wire   [4:0] or_ln172_fu_292_p2;
wire   [5:0] tmp_s_fu_312_p3;
wire   [31:0] zext_ln172_fu_288_p1;
wire   [31:0] zext_ln172_1_fu_298_p1;
wire   [4:0] or_ln172_1_fu_340_p2;
wire   [31:0] zext_ln174_fu_346_p1;
wire   [4:0] or_ln172_2_fu_356_p2;
wire   [31:0] zext_ln174_1_fu_362_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 x_fu_72 = 6'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U180(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add234_1_reg_547),
    .din1(l_new),
    .ce(1'b1),
    .dout(grp_fu_256_p2)
);

flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U181(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add234_2_reg_552),
    .din1(l_new),
    .ce(1'b1),
    .dout(grp_fu_260_p2)
);

flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U182(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add234_3_reg_557),
    .din1(l_new),
    .ce(1'b1),
    .dout(grp_fu_264_p2)
);

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter26_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_fu_276_p3 == 1'd0))) begin
            x_fu_72 <= add_ln172_fu_372_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_72 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_addr_reg_428 <= zext_ln176_fu_320_p1;
        acc_1_addr_reg_428_pp0_iter1_reg <= acc_1_addr_reg_428;
        acc_2_addr_reg_434 <= zext_ln176_fu_320_p1;
        acc_2_addr_reg_434_pp0_iter1_reg <= acc_2_addr_reg_434;
        acc_3_addr_reg_440 <= zext_ln176_fu_320_p1;
        acc_3_addr_reg_440_pp0_iter1_reg <= acc_3_addr_reg_440;
        acc_addr_reg_422 <= zext_ln176_fu_320_p1;
        acc_addr_reg_422_pp0_iter1_reg <= acc_addr_reg_422;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln174_1_reg_450 <= icmp_ln174_1_fu_334_p2;
        icmp_ln174_1_reg_450_pp0_iter1_reg <= icmp_ln174_1_reg_450;
        icmp_ln174_2_reg_454 <= icmp_ln174_2_fu_350_p2;
        icmp_ln174_2_reg_454_pp0_iter1_reg <= icmp_ln174_2_reg_454;
        icmp_ln174_3_reg_458 <= icmp_ln174_3_fu_366_p2;
        icmp_ln174_3_reg_458_pp0_iter1_reg <= icmp_ln174_3_reg_458;
        icmp_ln174_reg_446 <= icmp_ln174_fu_328_p2;
        icmp_ln174_reg_446_pp0_iter1_reg <= icmp_ln174_reg_446;
        lshr_ln5_reg_417 <= {{ap_sig_allocacmp_x_3[4:2]}};
        lshr_ln5_reg_417_pp0_iter1_reg <= lshr_ln5_reg_417;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_1_addr_reg_428_pp0_iter10_reg <= acc_1_addr_reg_428_pp0_iter9_reg;
        acc_1_addr_reg_428_pp0_iter11_reg <= acc_1_addr_reg_428_pp0_iter10_reg;
        acc_1_addr_reg_428_pp0_iter12_reg <= acc_1_addr_reg_428_pp0_iter11_reg;
        acc_1_addr_reg_428_pp0_iter13_reg <= acc_1_addr_reg_428_pp0_iter12_reg;
        acc_1_addr_reg_428_pp0_iter14_reg <= acc_1_addr_reg_428_pp0_iter13_reg;
        acc_1_addr_reg_428_pp0_iter15_reg <= acc_1_addr_reg_428_pp0_iter14_reg;
        acc_1_addr_reg_428_pp0_iter16_reg <= acc_1_addr_reg_428_pp0_iter15_reg;
        acc_1_addr_reg_428_pp0_iter17_reg <= acc_1_addr_reg_428_pp0_iter16_reg;
        acc_1_addr_reg_428_pp0_iter18_reg <= acc_1_addr_reg_428_pp0_iter17_reg;
        acc_1_addr_reg_428_pp0_iter19_reg <= acc_1_addr_reg_428_pp0_iter18_reg;
        acc_1_addr_reg_428_pp0_iter20_reg <= acc_1_addr_reg_428_pp0_iter19_reg;
        acc_1_addr_reg_428_pp0_iter21_reg <= acc_1_addr_reg_428_pp0_iter20_reg;
        acc_1_addr_reg_428_pp0_iter22_reg <= acc_1_addr_reg_428_pp0_iter21_reg;
        acc_1_addr_reg_428_pp0_iter23_reg <= acc_1_addr_reg_428_pp0_iter22_reg;
        acc_1_addr_reg_428_pp0_iter24_reg <= acc_1_addr_reg_428_pp0_iter23_reg;
        acc_1_addr_reg_428_pp0_iter25_reg <= acc_1_addr_reg_428_pp0_iter24_reg;
        acc_1_addr_reg_428_pp0_iter26_reg <= acc_1_addr_reg_428_pp0_iter25_reg;
        acc_1_addr_reg_428_pp0_iter2_reg <= acc_1_addr_reg_428_pp0_iter1_reg;
        acc_1_addr_reg_428_pp0_iter3_reg <= acc_1_addr_reg_428_pp0_iter2_reg;
        acc_1_addr_reg_428_pp0_iter4_reg <= acc_1_addr_reg_428_pp0_iter3_reg;
        acc_1_addr_reg_428_pp0_iter5_reg <= acc_1_addr_reg_428_pp0_iter4_reg;
        acc_1_addr_reg_428_pp0_iter6_reg <= acc_1_addr_reg_428_pp0_iter5_reg;
        acc_1_addr_reg_428_pp0_iter7_reg <= acc_1_addr_reg_428_pp0_iter6_reg;
        acc_1_addr_reg_428_pp0_iter8_reg <= acc_1_addr_reg_428_pp0_iter7_reg;
        acc_1_addr_reg_428_pp0_iter9_reg <= acc_1_addr_reg_428_pp0_iter8_reg;
        acc_2_addr_reg_434_pp0_iter10_reg <= acc_2_addr_reg_434_pp0_iter9_reg;
        acc_2_addr_reg_434_pp0_iter11_reg <= acc_2_addr_reg_434_pp0_iter10_reg;
        acc_2_addr_reg_434_pp0_iter12_reg <= acc_2_addr_reg_434_pp0_iter11_reg;
        acc_2_addr_reg_434_pp0_iter13_reg <= acc_2_addr_reg_434_pp0_iter12_reg;
        acc_2_addr_reg_434_pp0_iter14_reg <= acc_2_addr_reg_434_pp0_iter13_reg;
        acc_2_addr_reg_434_pp0_iter15_reg <= acc_2_addr_reg_434_pp0_iter14_reg;
        acc_2_addr_reg_434_pp0_iter16_reg <= acc_2_addr_reg_434_pp0_iter15_reg;
        acc_2_addr_reg_434_pp0_iter17_reg <= acc_2_addr_reg_434_pp0_iter16_reg;
        acc_2_addr_reg_434_pp0_iter18_reg <= acc_2_addr_reg_434_pp0_iter17_reg;
        acc_2_addr_reg_434_pp0_iter19_reg <= acc_2_addr_reg_434_pp0_iter18_reg;
        acc_2_addr_reg_434_pp0_iter20_reg <= acc_2_addr_reg_434_pp0_iter19_reg;
        acc_2_addr_reg_434_pp0_iter21_reg <= acc_2_addr_reg_434_pp0_iter20_reg;
        acc_2_addr_reg_434_pp0_iter22_reg <= acc_2_addr_reg_434_pp0_iter21_reg;
        acc_2_addr_reg_434_pp0_iter23_reg <= acc_2_addr_reg_434_pp0_iter22_reg;
        acc_2_addr_reg_434_pp0_iter24_reg <= acc_2_addr_reg_434_pp0_iter23_reg;
        acc_2_addr_reg_434_pp0_iter25_reg <= acc_2_addr_reg_434_pp0_iter24_reg;
        acc_2_addr_reg_434_pp0_iter26_reg <= acc_2_addr_reg_434_pp0_iter25_reg;
        acc_2_addr_reg_434_pp0_iter2_reg <= acc_2_addr_reg_434_pp0_iter1_reg;
        acc_2_addr_reg_434_pp0_iter3_reg <= acc_2_addr_reg_434_pp0_iter2_reg;
        acc_2_addr_reg_434_pp0_iter4_reg <= acc_2_addr_reg_434_pp0_iter3_reg;
        acc_2_addr_reg_434_pp0_iter5_reg <= acc_2_addr_reg_434_pp0_iter4_reg;
        acc_2_addr_reg_434_pp0_iter6_reg <= acc_2_addr_reg_434_pp0_iter5_reg;
        acc_2_addr_reg_434_pp0_iter7_reg <= acc_2_addr_reg_434_pp0_iter6_reg;
        acc_2_addr_reg_434_pp0_iter8_reg <= acc_2_addr_reg_434_pp0_iter7_reg;
        acc_2_addr_reg_434_pp0_iter9_reg <= acc_2_addr_reg_434_pp0_iter8_reg;
        acc_3_addr_reg_440_pp0_iter10_reg <= acc_3_addr_reg_440_pp0_iter9_reg;
        acc_3_addr_reg_440_pp0_iter11_reg <= acc_3_addr_reg_440_pp0_iter10_reg;
        acc_3_addr_reg_440_pp0_iter12_reg <= acc_3_addr_reg_440_pp0_iter11_reg;
        acc_3_addr_reg_440_pp0_iter13_reg <= acc_3_addr_reg_440_pp0_iter12_reg;
        acc_3_addr_reg_440_pp0_iter14_reg <= acc_3_addr_reg_440_pp0_iter13_reg;
        acc_3_addr_reg_440_pp0_iter15_reg <= acc_3_addr_reg_440_pp0_iter14_reg;
        acc_3_addr_reg_440_pp0_iter16_reg <= acc_3_addr_reg_440_pp0_iter15_reg;
        acc_3_addr_reg_440_pp0_iter17_reg <= acc_3_addr_reg_440_pp0_iter16_reg;
        acc_3_addr_reg_440_pp0_iter18_reg <= acc_3_addr_reg_440_pp0_iter17_reg;
        acc_3_addr_reg_440_pp0_iter19_reg <= acc_3_addr_reg_440_pp0_iter18_reg;
        acc_3_addr_reg_440_pp0_iter20_reg <= acc_3_addr_reg_440_pp0_iter19_reg;
        acc_3_addr_reg_440_pp0_iter21_reg <= acc_3_addr_reg_440_pp0_iter20_reg;
        acc_3_addr_reg_440_pp0_iter22_reg <= acc_3_addr_reg_440_pp0_iter21_reg;
        acc_3_addr_reg_440_pp0_iter23_reg <= acc_3_addr_reg_440_pp0_iter22_reg;
        acc_3_addr_reg_440_pp0_iter24_reg <= acc_3_addr_reg_440_pp0_iter23_reg;
        acc_3_addr_reg_440_pp0_iter25_reg <= acc_3_addr_reg_440_pp0_iter24_reg;
        acc_3_addr_reg_440_pp0_iter26_reg <= acc_3_addr_reg_440_pp0_iter25_reg;
        acc_3_addr_reg_440_pp0_iter2_reg <= acc_3_addr_reg_440_pp0_iter1_reg;
        acc_3_addr_reg_440_pp0_iter3_reg <= acc_3_addr_reg_440_pp0_iter2_reg;
        acc_3_addr_reg_440_pp0_iter4_reg <= acc_3_addr_reg_440_pp0_iter3_reg;
        acc_3_addr_reg_440_pp0_iter5_reg <= acc_3_addr_reg_440_pp0_iter4_reg;
        acc_3_addr_reg_440_pp0_iter6_reg <= acc_3_addr_reg_440_pp0_iter5_reg;
        acc_3_addr_reg_440_pp0_iter7_reg <= acc_3_addr_reg_440_pp0_iter6_reg;
        acc_3_addr_reg_440_pp0_iter8_reg <= acc_3_addr_reg_440_pp0_iter7_reg;
        acc_3_addr_reg_440_pp0_iter9_reg <= acc_3_addr_reg_440_pp0_iter8_reg;
        acc_addr_reg_422_pp0_iter10_reg <= acc_addr_reg_422_pp0_iter9_reg;
        acc_addr_reg_422_pp0_iter11_reg <= acc_addr_reg_422_pp0_iter10_reg;
        acc_addr_reg_422_pp0_iter12_reg <= acc_addr_reg_422_pp0_iter11_reg;
        acc_addr_reg_422_pp0_iter13_reg <= acc_addr_reg_422_pp0_iter12_reg;
        acc_addr_reg_422_pp0_iter14_reg <= acc_addr_reg_422_pp0_iter13_reg;
        acc_addr_reg_422_pp0_iter15_reg <= acc_addr_reg_422_pp0_iter14_reg;
        acc_addr_reg_422_pp0_iter16_reg <= acc_addr_reg_422_pp0_iter15_reg;
        acc_addr_reg_422_pp0_iter17_reg <= acc_addr_reg_422_pp0_iter16_reg;
        acc_addr_reg_422_pp0_iter18_reg <= acc_addr_reg_422_pp0_iter17_reg;
        acc_addr_reg_422_pp0_iter19_reg <= acc_addr_reg_422_pp0_iter18_reg;
        acc_addr_reg_422_pp0_iter20_reg <= acc_addr_reg_422_pp0_iter19_reg;
        acc_addr_reg_422_pp0_iter21_reg <= acc_addr_reg_422_pp0_iter20_reg;
        acc_addr_reg_422_pp0_iter22_reg <= acc_addr_reg_422_pp0_iter21_reg;
        acc_addr_reg_422_pp0_iter23_reg <= acc_addr_reg_422_pp0_iter22_reg;
        acc_addr_reg_422_pp0_iter24_reg <= acc_addr_reg_422_pp0_iter23_reg;
        acc_addr_reg_422_pp0_iter25_reg <= acc_addr_reg_422_pp0_iter24_reg;
        acc_addr_reg_422_pp0_iter26_reg <= acc_addr_reg_422_pp0_iter25_reg;
        acc_addr_reg_422_pp0_iter2_reg <= acc_addr_reg_422_pp0_iter1_reg;
        acc_addr_reg_422_pp0_iter3_reg <= acc_addr_reg_422_pp0_iter2_reg;
        acc_addr_reg_422_pp0_iter4_reg <= acc_addr_reg_422_pp0_iter3_reg;
        acc_addr_reg_422_pp0_iter5_reg <= acc_addr_reg_422_pp0_iter4_reg;
        acc_addr_reg_422_pp0_iter6_reg <= acc_addr_reg_422_pp0_iter5_reg;
        acc_addr_reg_422_pp0_iter7_reg <= acc_addr_reg_422_pp0_iter6_reg;
        acc_addr_reg_422_pp0_iter8_reg <= acc_addr_reg_422_pp0_iter7_reg;
        acc_addr_reg_422_pp0_iter9_reg <= acc_addr_reg_422_pp0_iter8_reg;
        add1_reg_542 <= grp_fu_2294_p_dout0;
        add234_1_reg_547 <= grp_fu_2298_p_dout0;
        add234_2_reg_552 <= grp_fu_2302_p_dout0;
        add234_3_reg_557 <= grp_fu_2306_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        div235_1_reg_567 <= grp_fu_256_p2;
        div235_2_reg_572 <= grp_fu_260_p2;
        div235_3_reg_577 <= grp_fu_264_p2;
        div_reg_562 <= grp_fu_940_p_dout0;
        icmp_ln174_1_reg_450_pp0_iter10_reg <= icmp_ln174_1_reg_450_pp0_iter9_reg;
        icmp_ln174_1_reg_450_pp0_iter11_reg <= icmp_ln174_1_reg_450_pp0_iter10_reg;
        icmp_ln174_1_reg_450_pp0_iter12_reg <= icmp_ln174_1_reg_450_pp0_iter11_reg;
        icmp_ln174_1_reg_450_pp0_iter13_reg <= icmp_ln174_1_reg_450_pp0_iter12_reg;
        icmp_ln174_1_reg_450_pp0_iter14_reg <= icmp_ln174_1_reg_450_pp0_iter13_reg;
        icmp_ln174_1_reg_450_pp0_iter15_reg <= icmp_ln174_1_reg_450_pp0_iter14_reg;
        icmp_ln174_1_reg_450_pp0_iter16_reg <= icmp_ln174_1_reg_450_pp0_iter15_reg;
        icmp_ln174_1_reg_450_pp0_iter17_reg <= icmp_ln174_1_reg_450_pp0_iter16_reg;
        icmp_ln174_1_reg_450_pp0_iter18_reg <= icmp_ln174_1_reg_450_pp0_iter17_reg;
        icmp_ln174_1_reg_450_pp0_iter19_reg <= icmp_ln174_1_reg_450_pp0_iter18_reg;
        icmp_ln174_1_reg_450_pp0_iter20_reg <= icmp_ln174_1_reg_450_pp0_iter19_reg;
        icmp_ln174_1_reg_450_pp0_iter21_reg <= icmp_ln174_1_reg_450_pp0_iter20_reg;
        icmp_ln174_1_reg_450_pp0_iter22_reg <= icmp_ln174_1_reg_450_pp0_iter21_reg;
        icmp_ln174_1_reg_450_pp0_iter23_reg <= icmp_ln174_1_reg_450_pp0_iter22_reg;
        icmp_ln174_1_reg_450_pp0_iter24_reg <= icmp_ln174_1_reg_450_pp0_iter23_reg;
        icmp_ln174_1_reg_450_pp0_iter25_reg <= icmp_ln174_1_reg_450_pp0_iter24_reg;
        icmp_ln174_1_reg_450_pp0_iter26_reg <= icmp_ln174_1_reg_450_pp0_iter25_reg;
        icmp_ln174_1_reg_450_pp0_iter2_reg <= icmp_ln174_1_reg_450_pp0_iter1_reg;
        icmp_ln174_1_reg_450_pp0_iter3_reg <= icmp_ln174_1_reg_450_pp0_iter2_reg;
        icmp_ln174_1_reg_450_pp0_iter4_reg <= icmp_ln174_1_reg_450_pp0_iter3_reg;
        icmp_ln174_1_reg_450_pp0_iter5_reg <= icmp_ln174_1_reg_450_pp0_iter4_reg;
        icmp_ln174_1_reg_450_pp0_iter6_reg <= icmp_ln174_1_reg_450_pp0_iter5_reg;
        icmp_ln174_1_reg_450_pp0_iter7_reg <= icmp_ln174_1_reg_450_pp0_iter6_reg;
        icmp_ln174_1_reg_450_pp0_iter8_reg <= icmp_ln174_1_reg_450_pp0_iter7_reg;
        icmp_ln174_1_reg_450_pp0_iter9_reg <= icmp_ln174_1_reg_450_pp0_iter8_reg;
        icmp_ln174_2_reg_454_pp0_iter10_reg <= icmp_ln174_2_reg_454_pp0_iter9_reg;
        icmp_ln174_2_reg_454_pp0_iter11_reg <= icmp_ln174_2_reg_454_pp0_iter10_reg;
        icmp_ln174_2_reg_454_pp0_iter12_reg <= icmp_ln174_2_reg_454_pp0_iter11_reg;
        icmp_ln174_2_reg_454_pp0_iter13_reg <= icmp_ln174_2_reg_454_pp0_iter12_reg;
        icmp_ln174_2_reg_454_pp0_iter14_reg <= icmp_ln174_2_reg_454_pp0_iter13_reg;
        icmp_ln174_2_reg_454_pp0_iter15_reg <= icmp_ln174_2_reg_454_pp0_iter14_reg;
        icmp_ln174_2_reg_454_pp0_iter16_reg <= icmp_ln174_2_reg_454_pp0_iter15_reg;
        icmp_ln174_2_reg_454_pp0_iter17_reg <= icmp_ln174_2_reg_454_pp0_iter16_reg;
        icmp_ln174_2_reg_454_pp0_iter18_reg <= icmp_ln174_2_reg_454_pp0_iter17_reg;
        icmp_ln174_2_reg_454_pp0_iter19_reg <= icmp_ln174_2_reg_454_pp0_iter18_reg;
        icmp_ln174_2_reg_454_pp0_iter20_reg <= icmp_ln174_2_reg_454_pp0_iter19_reg;
        icmp_ln174_2_reg_454_pp0_iter21_reg <= icmp_ln174_2_reg_454_pp0_iter20_reg;
        icmp_ln174_2_reg_454_pp0_iter22_reg <= icmp_ln174_2_reg_454_pp0_iter21_reg;
        icmp_ln174_2_reg_454_pp0_iter23_reg <= icmp_ln174_2_reg_454_pp0_iter22_reg;
        icmp_ln174_2_reg_454_pp0_iter24_reg <= icmp_ln174_2_reg_454_pp0_iter23_reg;
        icmp_ln174_2_reg_454_pp0_iter25_reg <= icmp_ln174_2_reg_454_pp0_iter24_reg;
        icmp_ln174_2_reg_454_pp0_iter26_reg <= icmp_ln174_2_reg_454_pp0_iter25_reg;
        icmp_ln174_2_reg_454_pp0_iter2_reg <= icmp_ln174_2_reg_454_pp0_iter1_reg;
        icmp_ln174_2_reg_454_pp0_iter3_reg <= icmp_ln174_2_reg_454_pp0_iter2_reg;
        icmp_ln174_2_reg_454_pp0_iter4_reg <= icmp_ln174_2_reg_454_pp0_iter3_reg;
        icmp_ln174_2_reg_454_pp0_iter5_reg <= icmp_ln174_2_reg_454_pp0_iter4_reg;
        icmp_ln174_2_reg_454_pp0_iter6_reg <= icmp_ln174_2_reg_454_pp0_iter5_reg;
        icmp_ln174_2_reg_454_pp0_iter7_reg <= icmp_ln174_2_reg_454_pp0_iter6_reg;
        icmp_ln174_2_reg_454_pp0_iter8_reg <= icmp_ln174_2_reg_454_pp0_iter7_reg;
        icmp_ln174_2_reg_454_pp0_iter9_reg <= icmp_ln174_2_reg_454_pp0_iter8_reg;
        icmp_ln174_3_reg_458_pp0_iter10_reg <= icmp_ln174_3_reg_458_pp0_iter9_reg;
        icmp_ln174_3_reg_458_pp0_iter11_reg <= icmp_ln174_3_reg_458_pp0_iter10_reg;
        icmp_ln174_3_reg_458_pp0_iter12_reg <= icmp_ln174_3_reg_458_pp0_iter11_reg;
        icmp_ln174_3_reg_458_pp0_iter13_reg <= icmp_ln174_3_reg_458_pp0_iter12_reg;
        icmp_ln174_3_reg_458_pp0_iter14_reg <= icmp_ln174_3_reg_458_pp0_iter13_reg;
        icmp_ln174_3_reg_458_pp0_iter15_reg <= icmp_ln174_3_reg_458_pp0_iter14_reg;
        icmp_ln174_3_reg_458_pp0_iter16_reg <= icmp_ln174_3_reg_458_pp0_iter15_reg;
        icmp_ln174_3_reg_458_pp0_iter17_reg <= icmp_ln174_3_reg_458_pp0_iter16_reg;
        icmp_ln174_3_reg_458_pp0_iter18_reg <= icmp_ln174_3_reg_458_pp0_iter17_reg;
        icmp_ln174_3_reg_458_pp0_iter19_reg <= icmp_ln174_3_reg_458_pp0_iter18_reg;
        icmp_ln174_3_reg_458_pp0_iter20_reg <= icmp_ln174_3_reg_458_pp0_iter19_reg;
        icmp_ln174_3_reg_458_pp0_iter21_reg <= icmp_ln174_3_reg_458_pp0_iter20_reg;
        icmp_ln174_3_reg_458_pp0_iter22_reg <= icmp_ln174_3_reg_458_pp0_iter21_reg;
        icmp_ln174_3_reg_458_pp0_iter23_reg <= icmp_ln174_3_reg_458_pp0_iter22_reg;
        icmp_ln174_3_reg_458_pp0_iter24_reg <= icmp_ln174_3_reg_458_pp0_iter23_reg;
        icmp_ln174_3_reg_458_pp0_iter25_reg <= icmp_ln174_3_reg_458_pp0_iter24_reg;
        icmp_ln174_3_reg_458_pp0_iter26_reg <= icmp_ln174_3_reg_458_pp0_iter25_reg;
        icmp_ln174_3_reg_458_pp0_iter2_reg <= icmp_ln174_3_reg_458_pp0_iter1_reg;
        icmp_ln174_3_reg_458_pp0_iter3_reg <= icmp_ln174_3_reg_458_pp0_iter2_reg;
        icmp_ln174_3_reg_458_pp0_iter4_reg <= icmp_ln174_3_reg_458_pp0_iter3_reg;
        icmp_ln174_3_reg_458_pp0_iter5_reg <= icmp_ln174_3_reg_458_pp0_iter4_reg;
        icmp_ln174_3_reg_458_pp0_iter6_reg <= icmp_ln174_3_reg_458_pp0_iter5_reg;
        icmp_ln174_3_reg_458_pp0_iter7_reg <= icmp_ln174_3_reg_458_pp0_iter6_reg;
        icmp_ln174_3_reg_458_pp0_iter8_reg <= icmp_ln174_3_reg_458_pp0_iter7_reg;
        icmp_ln174_3_reg_458_pp0_iter9_reg <= icmp_ln174_3_reg_458_pp0_iter8_reg;
        icmp_ln174_reg_446_pp0_iter10_reg <= icmp_ln174_reg_446_pp0_iter9_reg;
        icmp_ln174_reg_446_pp0_iter11_reg <= icmp_ln174_reg_446_pp0_iter10_reg;
        icmp_ln174_reg_446_pp0_iter12_reg <= icmp_ln174_reg_446_pp0_iter11_reg;
        icmp_ln174_reg_446_pp0_iter13_reg <= icmp_ln174_reg_446_pp0_iter12_reg;
        icmp_ln174_reg_446_pp0_iter14_reg <= icmp_ln174_reg_446_pp0_iter13_reg;
        icmp_ln174_reg_446_pp0_iter15_reg <= icmp_ln174_reg_446_pp0_iter14_reg;
        icmp_ln174_reg_446_pp0_iter16_reg <= icmp_ln174_reg_446_pp0_iter15_reg;
        icmp_ln174_reg_446_pp0_iter17_reg <= icmp_ln174_reg_446_pp0_iter16_reg;
        icmp_ln174_reg_446_pp0_iter18_reg <= icmp_ln174_reg_446_pp0_iter17_reg;
        icmp_ln174_reg_446_pp0_iter19_reg <= icmp_ln174_reg_446_pp0_iter18_reg;
        icmp_ln174_reg_446_pp0_iter20_reg <= icmp_ln174_reg_446_pp0_iter19_reg;
        icmp_ln174_reg_446_pp0_iter21_reg <= icmp_ln174_reg_446_pp0_iter20_reg;
        icmp_ln174_reg_446_pp0_iter22_reg <= icmp_ln174_reg_446_pp0_iter21_reg;
        icmp_ln174_reg_446_pp0_iter23_reg <= icmp_ln174_reg_446_pp0_iter22_reg;
        icmp_ln174_reg_446_pp0_iter24_reg <= icmp_ln174_reg_446_pp0_iter23_reg;
        icmp_ln174_reg_446_pp0_iter25_reg <= icmp_ln174_reg_446_pp0_iter24_reg;
        icmp_ln174_reg_446_pp0_iter26_reg <= icmp_ln174_reg_446_pp0_iter25_reg;
        icmp_ln174_reg_446_pp0_iter2_reg <= icmp_ln174_reg_446_pp0_iter1_reg;
        icmp_ln174_reg_446_pp0_iter3_reg <= icmp_ln174_reg_446_pp0_iter2_reg;
        icmp_ln174_reg_446_pp0_iter4_reg <= icmp_ln174_reg_446_pp0_iter3_reg;
        icmp_ln174_reg_446_pp0_iter5_reg <= icmp_ln174_reg_446_pp0_iter4_reg;
        icmp_ln174_reg_446_pp0_iter6_reg <= icmp_ln174_reg_446_pp0_iter5_reg;
        icmp_ln174_reg_446_pp0_iter7_reg <= icmp_ln174_reg_446_pp0_iter6_reg;
        icmp_ln174_reg_446_pp0_iter8_reg <= icmp_ln174_reg_446_pp0_iter7_reg;
        icmp_ln174_reg_446_pp0_iter9_reg <= icmp_ln174_reg_446_pp0_iter8_reg;
        lshr_ln5_reg_417_pp0_iter2_reg <= lshr_ln5_reg_417_pp0_iter1_reg;
        lshr_ln5_reg_417_pp0_iter3_reg <= lshr_ln5_reg_417_pp0_iter2_reg;
        mul231_1_reg_512 <= grp_fu_2310_p_dout0;
        mul231_2_reg_522 <= grp_fu_2314_p_dout0;
        mul231_3_reg_532 <= grp_fu_2318_p_dout0;
        mul3_reg_502 <= grp_fu_936_p_dout0;
        weighted_1_load_reg_517 <= weighted_1_q0;
        weighted_2_load_reg_527 <= weighted_2_q0;
        weighted_3_load_reg_537 <= weighted_3_q0;
        weighted_load_reg_507 <= weighted_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_load_reg_467 <= acc_1_q1;
        acc_2_load_reg_472 <= acc_2_q1;
        acc_3_load_reg_477 <= acc_3_q1;
        acc_load_reg_462 <= acc_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_1_ce0 = 1'b1;
    end else begin
        acc_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_ce1 = 1'b1;
    end else begin
        acc_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln174_1_reg_450_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_1_we0 = 1'b1;
    end else begin
        acc_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_2_ce0 = 1'b1;
    end else begin
        acc_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_2_ce1 = 1'b1;
    end else begin
        acc_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln174_2_reg_454_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_2_we0 = 1'b1;
    end else begin
        acc_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_3_ce0 = 1'b1;
    end else begin
        acc_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_3_ce1 = 1'b1;
    end else begin
        acc_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln174_3_reg_458_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_3_we0 = 1'b1;
    end else begin
        acc_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_ce0 = 1'b1;
    end else begin
        acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_ce1 = 1'b1;
    end else begin
        acc_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln174_reg_446_pp0_iter26_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        acc_we0 = 1'b1;
    end else begin
        acc_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_fu_276_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter26_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_x_3 = 6'd0;
    end else begin
        ap_sig_allocacmp_x_3 = x_fu_72;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weighted_1_ce0 = 1'b1;
    end else begin
        weighted_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weighted_2_ce0 = 1'b1;
    end else begin
        weighted_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weighted_3_ce0 = 1'b1;
    end else begin
        weighted_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weighted_ce0 = 1'b1;
    end else begin
        weighted_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_address0 = acc_1_addr_reg_428_pp0_iter26_reg;

assign acc_1_address1 = zext_ln176_fu_320_p1;

assign acc_1_d0 = div235_1_reg_567;

assign acc_2_address0 = acc_2_addr_reg_434_pp0_iter26_reg;

assign acc_2_address1 = zext_ln176_fu_320_p1;

assign acc_2_d0 = div235_2_reg_572;

assign acc_3_address0 = acc_3_addr_reg_440_pp0_iter26_reg;

assign acc_3_address1 = zext_ln176_fu_320_p1;

assign acc_3_d0 = div235_3_reg_577;

assign acc_address0 = acc_addr_reg_422_pp0_iter26_reg;

assign acc_address1 = zext_ln176_fu_320_p1;

assign acc_d0 = div_reg_562;

assign add_ln172_fu_372_p2 = (ap_sig_allocacmp_x_3 + 6'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_2294_p_ce = 1'b1;

assign grp_fu_2294_p_din0 = mul3_reg_502;

assign grp_fu_2294_p_din1 = weighted_load_reg_507;

assign grp_fu_2294_p_opcode = 2'd0;

assign grp_fu_2298_p_ce = 1'b1;

assign grp_fu_2298_p_din0 = mul231_1_reg_512;

assign grp_fu_2298_p_din1 = weighted_1_load_reg_517;

assign grp_fu_2298_p_opcode = 2'd0;

assign grp_fu_2302_p_ce = 1'b1;

assign grp_fu_2302_p_din0 = mul231_2_reg_522;

assign grp_fu_2302_p_din1 = weighted_2_load_reg_527;

assign grp_fu_2302_p_opcode = 2'd0;

assign grp_fu_2306_p_ce = 1'b1;

assign grp_fu_2306_p_din0 = mul231_3_reg_532;

assign grp_fu_2306_p_din1 = weighted_3_load_reg_537;

assign grp_fu_2306_p_opcode = 2'd0;

assign grp_fu_2310_p_ce = 1'b1;

assign grp_fu_2310_p_din0 = mul1;

assign grp_fu_2310_p_din1 = acc_1_load_reg_467;

assign grp_fu_2314_p_ce = 1'b1;

assign grp_fu_2314_p_din0 = mul1;

assign grp_fu_2314_p_din1 = acc_2_load_reg_472;

assign grp_fu_2318_p_ce = 1'b1;

assign grp_fu_2318_p_din0 = mul1;

assign grp_fu_2318_p_din1 = acc_3_load_reg_477;

assign grp_fu_936_p_ce = 1'b1;

assign grp_fu_936_p_din0 = mul1;

assign grp_fu_936_p_din1 = acc_load_reg_462;

assign grp_fu_940_p_ce = 1'b1;

assign grp_fu_940_p_din0 = add1_reg_542;

assign grp_fu_940_p_din1 = l_new;

assign icmp_ln174_1_fu_334_p2 = (($signed(zext_ln172_1_fu_298_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln174_2_fu_350_p2 = (($signed(zext_ln174_fu_346_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln174_3_fu_366_p2 = (($signed(zext_ln174_1_fu_362_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_328_p2 = (($signed(zext_ln172_fu_288_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign lshr_ln5_fu_302_p4 = {{ap_sig_allocacmp_x_3[4:2]}};

assign or_ln172_1_fu_340_p2 = (trunc_ln172_fu_284_p1 | 5'd2);

assign or_ln172_2_fu_356_p2 = (trunc_ln172_fu_284_p1 | 5'd3);

assign or_ln172_fu_292_p2 = (trunc_ln172_fu_284_p1 | 5'd1);

assign tmp_fu_276_p3 = ap_sig_allocacmp_x_3[32'd5];

assign tmp_s_fu_312_p3 = {{i_4}, {lshr_ln5_fu_302_p4}};

assign trunc_ln172_fu_284_p1 = ap_sig_allocacmp_x_3[4:0];

assign weighted_1_address0 = zext_ln172_2_fu_383_p1;

assign weighted_2_address0 = zext_ln172_2_fu_383_p1;

assign weighted_3_address0 = zext_ln172_2_fu_383_p1;

assign weighted_address0 = zext_ln172_2_fu_383_p1;

assign zext_ln172_1_fu_298_p1 = or_ln172_fu_292_p2;

assign zext_ln172_2_fu_383_p1 = lshr_ln5_reg_417_pp0_iter3_reg;

assign zext_ln172_fu_288_p1 = ap_sig_allocacmp_x_3;

assign zext_ln174_1_fu_362_p1 = or_ln172_2_fu_356_p2;

assign zext_ln174_fu_346_p1 = or_ln172_1_fu_340_p2;

assign zext_ln176_fu_320_p1 = tmp_s_fu_312_p3;

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_UPDATE_ACC
