// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_FIND_MAX (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        k_lim,
        zext_ln138,
        scores_address0,
        scores_ce0,
        scores_q0,
        tile_max_out,
        tile_max_out_ap_vld,
        grp_fu_948_p_din0,
        grp_fu_948_p_din1,
        grp_fu_948_p_opcode,
        grp_fu_948_p_dout0,
        grp_fu_948_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] k_lim;
input  [5:0] zext_ln138;
output  [5:0] scores_address0;
output   scores_ce0;
input  [31:0] scores_q0;
output  [31:0] tile_max_out;
output   tile_max_out_ap_vld;
output  [31:0] grp_fu_948_p_din0;
output  [31:0] grp_fu_948_p_din1;
output  [4:0] grp_fu_948_p_opcode;
input  [0:0] grp_fu_948_p_dout0;
output   grp_fu_948_p_ce;

reg ap_idle;
reg scores_ce0;
reg tile_max_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln136_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln136_reg_252;
reg   [31:0] tile_max_load_1_reg_261;
reg   [31:0] tile_max_1_reg_267;
wire   [0:0] icmp_ln138_fu_178_p2;
reg   [0:0] icmp_ln138_reg_273;
wire   [0:0] icmp_ln138_1_fu_184_p2;
reg   [0:0] icmp_ln138_1_reg_278;
wire   [0:0] icmp_ln138_2_fu_190_p2;
reg   [0:0] icmp_ln138_2_reg_283;
wire   [0:0] icmp_ln138_3_fu_196_p2;
reg   [0:0] icmp_ln138_3_reg_288;
wire   [63:0] zext_ln138_1_fu_128_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] tile_max_fu_44;
wire   [31:0] tile_max_2_fu_222_p3;
reg   [31:0] ap_sig_allocacmp_tile_max_load_1;
wire    ap_loop_init;
reg   [30:0] j_fu_48;
wire   [30:0] add_ln136_fu_112_p2;
reg   [30:0] ap_sig_allocacmp_j_2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] zext_ln136_fu_102_p1;
wire   [5:0] trunc_ln138_fu_118_p1;
wire   [5:0] add_ln138_fu_122_p2;
wire   [31:0] bitcast_ln138_fu_142_p1;
wire   [31:0] bitcast_ln138_1_fu_160_p1;
wire   [7:0] tmp_2_fu_146_p4;
wire   [22:0] trunc_ln138_1_fu_156_p1;
wire   [7:0] tmp_3_fu_164_p4;
wire   [22:0] trunc_ln138_2_fu_174_p1;
wire   [0:0] or_ln138_fu_202_p2;
wire   [0:0] and_ln138_fu_210_p2;
wire   [0:0] or_ln138_1_fu_206_p2;
wire   [0:0] and_ln138_1_fu_216_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 tile_max_fu_44 = 32'd0;
#0 j_fu_48 = 31'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln136_fu_106_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_48 <= add_ln136_fu_112_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_48 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            tile_max_fu_44 <= 32'd4048155338;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            tile_max_fu_44 <= tile_max_2_fu_222_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln136_reg_252 <= icmp_ln136_fu_106_p2;
        icmp_ln138_1_reg_278 <= icmp_ln138_1_fu_184_p2;
        icmp_ln138_2_reg_283 <= icmp_ln138_2_fu_190_p2;
        icmp_ln138_3_reg_288 <= icmp_ln138_3_fu_196_p2;
        icmp_ln138_reg_273 <= icmp_ln138_fu_178_p2;
        tile_max_1_reg_267 <= scores_q0;
        tile_max_load_1_reg_261 <= ap_sig_allocacmp_tile_max_load_1;
    end
end

always @ (*) begin
    if (((icmp_ln136_fu_106_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_2 = 31'd0;
    end else begin
        ap_sig_allocacmp_j_2 = j_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_tile_max_load_1 = tile_max_2_fu_222_p3;
    end else begin
        ap_sig_allocacmp_tile_max_load_1 = tile_max_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        scores_ce0 = 1'b1;
    end else begin
        scores_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln136_reg_252 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tile_max_out_ap_vld = 1'b1;
    end else begin
        tile_max_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln136_fu_112_p2 = (ap_sig_allocacmp_j_2 + 31'd1);

assign add_ln138_fu_122_p2 = (zext_ln138 + trunc_ln138_fu_118_p1);

assign and_ln138_1_fu_216_p2 = (or_ln138_1_fu_206_p2 & and_ln138_fu_210_p2);

assign and_ln138_fu_210_p2 = (or_ln138_fu_202_p2 & grp_fu_948_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln138_1_fu_160_p1 = ap_sig_allocacmp_tile_max_load_1;

assign bitcast_ln138_fu_142_p1 = scores_q0;

assign grp_fu_948_p_ce = 1'b1;

assign grp_fu_948_p_din0 = scores_q0;

assign grp_fu_948_p_din1 = ap_sig_allocacmp_tile_max_load_1;

assign grp_fu_948_p_opcode = 5'd2;

assign icmp_ln136_fu_106_p2 = (($signed(zext_ln136_fu_102_p1) < $signed(k_lim)) ? 1'b1 : 1'b0);

assign icmp_ln138_1_fu_184_p2 = ((trunc_ln138_1_fu_156_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln138_2_fu_190_p2 = ((tmp_3_fu_164_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln138_3_fu_196_p2 = ((trunc_ln138_2_fu_174_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_178_p2 = ((tmp_2_fu_146_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln138_1_fu_206_p2 = (icmp_ln138_3_reg_288 | icmp_ln138_2_reg_283);

assign or_ln138_fu_202_p2 = (icmp_ln138_reg_273 | icmp_ln138_1_reg_278);

assign scores_address0 = zext_ln138_1_fu_128_p1;

assign tile_max_2_fu_222_p3 = ((and_ln138_1_fu_216_p2[0:0] == 1'b1) ? tile_max_1_reg_267 : tile_max_load_1_reg_261);

assign tile_max_out = tile_max_fu_44;

assign tmp_2_fu_146_p4 = {{bitcast_ln138_fu_142_p1[30:23]}};

assign tmp_3_fu_164_p4 = {{bitcast_ln138_1_fu_160_p1[30:23]}};

assign trunc_ln138_1_fu_156_p1 = bitcast_ln138_fu_142_p1[22:0];

assign trunc_ln138_2_fu_174_p1 = bitcast_ln138_1_fu_160_p1[22:0];

assign trunc_ln138_fu_118_p1 = ap_sig_allocacmp_j_2[5:0];

assign zext_ln136_fu_102_p1 = ap_sig_allocacmp_j_2;

assign zext_ln138_1_fu_128_p1 = add_ln138_fu_122_p2;

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_FIND_MAX
