// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_VITIS_LOOP_160_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d,
        j_3,
        Vbuf_address0,
        Vbuf_ce0,
        Vbuf_q0,
        Vbuf_1_address0,
        Vbuf_1_ce0,
        Vbuf_1_q0,
        Vbuf_2_address0,
        Vbuf_2_ce0,
        Vbuf_2_q0,
        Vbuf_3_address0,
        Vbuf_3_ce0,
        Vbuf_3_q0,
        weighted_3_address0,
        weighted_3_ce0,
        weighted_3_we0,
        weighted_3_d0,
        weighted_3_address1,
        weighted_3_ce1,
        weighted_3_q1,
        weighted_2_address0,
        weighted_2_ce0,
        weighted_2_we0,
        weighted_2_d0,
        weighted_2_address1,
        weighted_2_ce1,
        weighted_2_q1,
        weighted_1_address0,
        weighted_1_ce0,
        weighted_1_we0,
        weighted_1_d0,
        weighted_1_address1,
        weighted_1_ce1,
        weighted_1_q1,
        weighted_address0,
        weighted_ce0,
        weighted_we0,
        weighted_d0,
        weighted_address1,
        weighted_ce1,
        weighted_q1,
        e,
        grp_fu_2294_p_din0,
        grp_fu_2294_p_din1,
        grp_fu_2294_p_opcode,
        grp_fu_2294_p_dout0,
        grp_fu_2294_p_ce,
        grp_fu_2298_p_din0,
        grp_fu_2298_p_din1,
        grp_fu_2298_p_opcode,
        grp_fu_2298_p_dout0,
        grp_fu_2298_p_ce,
        grp_fu_2302_p_din0,
        grp_fu_2302_p_din1,
        grp_fu_2302_p_opcode,
        grp_fu_2302_p_dout0,
        grp_fu_2302_p_ce,
        grp_fu_2306_p_din0,
        grp_fu_2306_p_din1,
        grp_fu_2306_p_opcode,
        grp_fu_2306_p_dout0,
        grp_fu_2306_p_ce,
        grp_fu_936_p_din0,
        grp_fu_936_p_din1,
        grp_fu_936_p_dout0,
        grp_fu_936_p_ce,
        grp_fu_2310_p_din0,
        grp_fu_2310_p_din1,
        grp_fu_2310_p_dout0,
        grp_fu_2310_p_ce,
        grp_fu_2314_p_din0,
        grp_fu_2314_p_din1,
        grp_fu_2314_p_dout0,
        grp_fu_2314_p_ce,
        grp_fu_2318_p_din0,
        grp_fu_2318_p_din1,
        grp_fu_2318_p_dout0,
        grp_fu_2318_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] d;
input  [2:0] j_3;
output  [5:0] Vbuf_address0;
output   Vbuf_ce0;
input  [31:0] Vbuf_q0;
output  [5:0] Vbuf_1_address0;
output   Vbuf_1_ce0;
input  [31:0] Vbuf_1_q0;
output  [5:0] Vbuf_2_address0;
output   Vbuf_2_ce0;
input  [31:0] Vbuf_2_q0;
output  [5:0] Vbuf_3_address0;
output   Vbuf_3_ce0;
input  [31:0] Vbuf_3_q0;
output  [2:0] weighted_3_address0;
output   weighted_3_ce0;
output   weighted_3_we0;
output  [31:0] weighted_3_d0;
output  [2:0] weighted_3_address1;
output   weighted_3_ce1;
input  [31:0] weighted_3_q1;
output  [2:0] weighted_2_address0;
output   weighted_2_ce0;
output   weighted_2_we0;
output  [31:0] weighted_2_d0;
output  [2:0] weighted_2_address1;
output   weighted_2_ce1;
input  [31:0] weighted_2_q1;
output  [2:0] weighted_1_address0;
output   weighted_1_ce0;
output   weighted_1_we0;
output  [31:0] weighted_1_d0;
output  [2:0] weighted_1_address1;
output   weighted_1_ce1;
input  [31:0] weighted_1_q1;
output  [2:0] weighted_address0;
output   weighted_ce0;
output   weighted_we0;
output  [31:0] weighted_d0;
output  [2:0] weighted_address1;
output   weighted_ce1;
input  [31:0] weighted_q1;
input  [31:0] e;
output  [31:0] grp_fu_2294_p_din0;
output  [31:0] grp_fu_2294_p_din1;
output  [1:0] grp_fu_2294_p_opcode;
input  [31:0] grp_fu_2294_p_dout0;
output   grp_fu_2294_p_ce;
output  [31:0] grp_fu_2298_p_din0;
output  [31:0] grp_fu_2298_p_din1;
output  [1:0] grp_fu_2298_p_opcode;
input  [31:0] grp_fu_2298_p_dout0;
output   grp_fu_2298_p_ce;
output  [31:0] grp_fu_2302_p_din0;
output  [31:0] grp_fu_2302_p_din1;
output  [1:0] grp_fu_2302_p_opcode;
input  [31:0] grp_fu_2302_p_dout0;
output   grp_fu_2302_p_ce;
output  [31:0] grp_fu_2306_p_din0;
output  [31:0] grp_fu_2306_p_din1;
output  [1:0] grp_fu_2306_p_opcode;
input  [31:0] grp_fu_2306_p_dout0;
output   grp_fu_2306_p_ce;
output  [31:0] grp_fu_936_p_din0;
output  [31:0] grp_fu_936_p_din1;
input  [31:0] grp_fu_936_p_dout0;
output   grp_fu_936_p_ce;
output  [31:0] grp_fu_2310_p_din0;
output  [31:0] grp_fu_2310_p_din1;
input  [31:0] grp_fu_2310_p_dout0;
output   grp_fu_2310_p_ce;
output  [31:0] grp_fu_2314_p_din0;
output  [31:0] grp_fu_2314_p_din1;
input  [31:0] grp_fu_2314_p_dout0;
output   grp_fu_2314_p_ce;
output  [31:0] grp_fu_2318_p_din0;
output  [31:0] grp_fu_2318_p_din1;
input  [31:0] grp_fu_2318_p_dout0;
output   grp_fu_2318_p_ce;

reg ap_idle;
reg Vbuf_ce0;
reg Vbuf_1_ce0;
reg Vbuf_2_ce0;
reg Vbuf_3_ce0;
reg weighted_3_ce0;
reg weighted_3_we0;
reg weighted_3_ce1;
reg weighted_2_ce0;
reg weighted_2_we0;
reg weighted_2_ce1;
reg weighted_1_ce0;
reg weighted_1_we0;
reg weighted_1_ce1;
reg weighted_ce0;
reg weighted_we0;
reg weighted_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_252_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] lshr_ln4_fu_278_p4;
reg   [2:0] lshr_ln4_reg_385;
reg   [2:0] lshr_ln4_reg_385_pp0_iter1_reg;
reg   [2:0] lshr_ln4_reg_385_pp0_iter2_reg;
reg   [2:0] lshr_ln4_reg_385_pp0_iter3_reg;
wire   [0:0] icmp_ln162_fu_304_p2;
reg   [0:0] icmp_ln162_reg_410;
reg   [0:0] icmp_ln162_reg_410_pp0_iter1_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter2_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter3_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter4_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter5_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter6_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter7_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter8_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter9_reg;
reg   [0:0] icmp_ln162_reg_410_pp0_iter10_reg;
wire   [0:0] icmp_ln162_1_fu_310_p2;
reg   [0:0] icmp_ln162_1_reg_414;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter1_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter2_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter3_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter4_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter5_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter6_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter7_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter8_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter9_reg;
reg   [0:0] icmp_ln162_1_reg_414_pp0_iter10_reg;
wire   [0:0] icmp_ln162_2_fu_326_p2;
reg   [0:0] icmp_ln162_2_reg_418;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter1_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter2_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter3_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter4_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter5_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter6_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter7_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter8_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter9_reg;
reg   [0:0] icmp_ln162_2_reg_418_pp0_iter10_reg;
wire   [0:0] icmp_ln162_3_fu_342_p2;
reg   [0:0] icmp_ln162_3_reg_422;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter1_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter2_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter3_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter4_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter5_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter6_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter7_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter8_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter9_reg;
reg   [0:0] icmp_ln162_3_reg_422_pp0_iter10_reg;
reg   [31:0] Vbuf_load_reg_426;
reg   [31:0] Vbuf_1_load_reg_431;
reg   [31:0] Vbuf_2_load_reg_436;
reg   [31:0] Vbuf_3_load_reg_441;
reg   [2:0] weighted_addr_reg_446;
reg   [2:0] weighted_addr_reg_446_pp0_iter5_reg;
reg   [2:0] weighted_addr_reg_446_pp0_iter6_reg;
reg   [2:0] weighted_addr_reg_446_pp0_iter7_reg;
reg   [2:0] weighted_addr_reg_446_pp0_iter8_reg;
reg   [2:0] weighted_addr_reg_446_pp0_iter9_reg;
reg   [2:0] weighted_addr_reg_446_pp0_iter10_reg;
reg   [2:0] weighted_1_addr_reg_452;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter5_reg;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter6_reg;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter7_reg;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter8_reg;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter9_reg;
reg   [2:0] weighted_1_addr_reg_452_pp0_iter10_reg;
reg   [2:0] weighted_2_addr_reg_458;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter5_reg;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter6_reg;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter7_reg;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter8_reg;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter9_reg;
reg   [2:0] weighted_2_addr_reg_458_pp0_iter10_reg;
reg   [2:0] weighted_3_addr_reg_464;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter5_reg;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter6_reg;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter7_reg;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter8_reg;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter9_reg;
reg   [2:0] weighted_3_addr_reg_464_pp0_iter10_reg;
reg   [31:0] mul2_reg_470;
reg   [31:0] weighted_load_reg_475;
reg   [31:0] mul202_1_reg_480;
reg   [31:0] weighted_1_load_reg_485;
reg   [31:0] mul202_2_reg_490;
reg   [31:0] weighted_2_load_reg_495;
reg   [31:0] mul202_3_reg_500;
reg   [31:0] weighted_3_load_reg_505;
reg   [31:0] add_reg_510;
reg   [31:0] add205_1_reg_515;
reg   [31:0] add205_2_reg_520;
reg   [31:0] add205_3_reg_525;
wire   [63:0] zext_ln162_2_fu_296_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln160_2_fu_359_p1;
reg   [5:0] x_fu_70;
wire   [5:0] add_ln160_fu_348_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_x_2;
wire   [4:0] trunc_ln160_fu_260_p1;
wire   [4:0] or_ln160_fu_268_p2;
wire   [5:0] tmp_s_fu_288_p3;
wire   [31:0] zext_ln160_fu_264_p1;
wire   [31:0] zext_ln160_1_fu_274_p1;
wire   [4:0] or_ln160_1_fu_316_p2;
wire   [31:0] zext_ln162_fu_322_p1;
wire   [4:0] or_ln160_2_fu_332_p2;
wire   [31:0] zext_ln162_1_fu_338_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 x_fu_70 = 6'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_252_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_70 <= add_ln160_fu_348_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_70 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Vbuf_1_load_reg_431 <= Vbuf_1_q0;
        Vbuf_2_load_reg_436 <= Vbuf_2_q0;
        Vbuf_3_load_reg_441 <= Vbuf_3_q0;
        Vbuf_load_reg_426 <= Vbuf_q0;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln162_1_reg_414 <= icmp_ln162_1_fu_310_p2;
        icmp_ln162_1_reg_414_pp0_iter1_reg <= icmp_ln162_1_reg_414;
        icmp_ln162_2_reg_418 <= icmp_ln162_2_fu_326_p2;
        icmp_ln162_2_reg_418_pp0_iter1_reg <= icmp_ln162_2_reg_418;
        icmp_ln162_3_reg_422 <= icmp_ln162_3_fu_342_p2;
        icmp_ln162_3_reg_422_pp0_iter1_reg <= icmp_ln162_3_reg_422;
        icmp_ln162_reg_410 <= icmp_ln162_fu_304_p2;
        icmp_ln162_reg_410_pp0_iter1_reg <= icmp_ln162_reg_410;
        lshr_ln4_reg_385 <= {{ap_sig_allocacmp_x_2[4:2]}};
        lshr_ln4_reg_385_pp0_iter1_reg <= lshr_ln4_reg_385;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add205_1_reg_515 <= grp_fu_2298_p_dout0;
        add205_2_reg_520 <= grp_fu_2302_p_dout0;
        add205_3_reg_525 <= grp_fu_2306_p_dout0;
        add_reg_510 <= grp_fu_2294_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln162_1_reg_414_pp0_iter10_reg <= icmp_ln162_1_reg_414_pp0_iter9_reg;
        icmp_ln162_1_reg_414_pp0_iter2_reg <= icmp_ln162_1_reg_414_pp0_iter1_reg;
        icmp_ln162_1_reg_414_pp0_iter3_reg <= icmp_ln162_1_reg_414_pp0_iter2_reg;
        icmp_ln162_1_reg_414_pp0_iter4_reg <= icmp_ln162_1_reg_414_pp0_iter3_reg;
        icmp_ln162_1_reg_414_pp0_iter5_reg <= icmp_ln162_1_reg_414_pp0_iter4_reg;
        icmp_ln162_1_reg_414_pp0_iter6_reg <= icmp_ln162_1_reg_414_pp0_iter5_reg;
        icmp_ln162_1_reg_414_pp0_iter7_reg <= icmp_ln162_1_reg_414_pp0_iter6_reg;
        icmp_ln162_1_reg_414_pp0_iter8_reg <= icmp_ln162_1_reg_414_pp0_iter7_reg;
        icmp_ln162_1_reg_414_pp0_iter9_reg <= icmp_ln162_1_reg_414_pp0_iter8_reg;
        icmp_ln162_2_reg_418_pp0_iter10_reg <= icmp_ln162_2_reg_418_pp0_iter9_reg;
        icmp_ln162_2_reg_418_pp0_iter2_reg <= icmp_ln162_2_reg_418_pp0_iter1_reg;
        icmp_ln162_2_reg_418_pp0_iter3_reg <= icmp_ln162_2_reg_418_pp0_iter2_reg;
        icmp_ln162_2_reg_418_pp0_iter4_reg <= icmp_ln162_2_reg_418_pp0_iter3_reg;
        icmp_ln162_2_reg_418_pp0_iter5_reg <= icmp_ln162_2_reg_418_pp0_iter4_reg;
        icmp_ln162_2_reg_418_pp0_iter6_reg <= icmp_ln162_2_reg_418_pp0_iter5_reg;
        icmp_ln162_2_reg_418_pp0_iter7_reg <= icmp_ln162_2_reg_418_pp0_iter6_reg;
        icmp_ln162_2_reg_418_pp0_iter8_reg <= icmp_ln162_2_reg_418_pp0_iter7_reg;
        icmp_ln162_2_reg_418_pp0_iter9_reg <= icmp_ln162_2_reg_418_pp0_iter8_reg;
        icmp_ln162_3_reg_422_pp0_iter10_reg <= icmp_ln162_3_reg_422_pp0_iter9_reg;
        icmp_ln162_3_reg_422_pp0_iter2_reg <= icmp_ln162_3_reg_422_pp0_iter1_reg;
        icmp_ln162_3_reg_422_pp0_iter3_reg <= icmp_ln162_3_reg_422_pp0_iter2_reg;
        icmp_ln162_3_reg_422_pp0_iter4_reg <= icmp_ln162_3_reg_422_pp0_iter3_reg;
        icmp_ln162_3_reg_422_pp0_iter5_reg <= icmp_ln162_3_reg_422_pp0_iter4_reg;
        icmp_ln162_3_reg_422_pp0_iter6_reg <= icmp_ln162_3_reg_422_pp0_iter5_reg;
        icmp_ln162_3_reg_422_pp0_iter7_reg <= icmp_ln162_3_reg_422_pp0_iter6_reg;
        icmp_ln162_3_reg_422_pp0_iter8_reg <= icmp_ln162_3_reg_422_pp0_iter7_reg;
        icmp_ln162_3_reg_422_pp0_iter9_reg <= icmp_ln162_3_reg_422_pp0_iter8_reg;
        icmp_ln162_reg_410_pp0_iter10_reg <= icmp_ln162_reg_410_pp0_iter9_reg;
        icmp_ln162_reg_410_pp0_iter2_reg <= icmp_ln162_reg_410_pp0_iter1_reg;
        icmp_ln162_reg_410_pp0_iter3_reg <= icmp_ln162_reg_410_pp0_iter2_reg;
        icmp_ln162_reg_410_pp0_iter4_reg <= icmp_ln162_reg_410_pp0_iter3_reg;
        icmp_ln162_reg_410_pp0_iter5_reg <= icmp_ln162_reg_410_pp0_iter4_reg;
        icmp_ln162_reg_410_pp0_iter6_reg <= icmp_ln162_reg_410_pp0_iter5_reg;
        icmp_ln162_reg_410_pp0_iter7_reg <= icmp_ln162_reg_410_pp0_iter6_reg;
        icmp_ln162_reg_410_pp0_iter8_reg <= icmp_ln162_reg_410_pp0_iter7_reg;
        icmp_ln162_reg_410_pp0_iter9_reg <= icmp_ln162_reg_410_pp0_iter8_reg;
        lshr_ln4_reg_385_pp0_iter2_reg <= lshr_ln4_reg_385_pp0_iter1_reg;
        lshr_ln4_reg_385_pp0_iter3_reg <= lshr_ln4_reg_385_pp0_iter2_reg;
        mul202_1_reg_480 <= grp_fu_2310_p_dout0;
        mul202_2_reg_490 <= grp_fu_2314_p_dout0;
        mul202_3_reg_500 <= grp_fu_2318_p_dout0;
        mul2_reg_470 <= grp_fu_936_p_dout0;
        weighted_1_addr_reg_452 <= zext_ln160_2_fu_359_p1;
        weighted_1_addr_reg_452_pp0_iter10_reg <= weighted_1_addr_reg_452_pp0_iter9_reg;
        weighted_1_addr_reg_452_pp0_iter5_reg <= weighted_1_addr_reg_452;
        weighted_1_addr_reg_452_pp0_iter6_reg <= weighted_1_addr_reg_452_pp0_iter5_reg;
        weighted_1_addr_reg_452_pp0_iter7_reg <= weighted_1_addr_reg_452_pp0_iter6_reg;
        weighted_1_addr_reg_452_pp0_iter8_reg <= weighted_1_addr_reg_452_pp0_iter7_reg;
        weighted_1_addr_reg_452_pp0_iter9_reg <= weighted_1_addr_reg_452_pp0_iter8_reg;
        weighted_2_addr_reg_458 <= zext_ln160_2_fu_359_p1;
        weighted_2_addr_reg_458_pp0_iter10_reg <= weighted_2_addr_reg_458_pp0_iter9_reg;
        weighted_2_addr_reg_458_pp0_iter5_reg <= weighted_2_addr_reg_458;
        weighted_2_addr_reg_458_pp0_iter6_reg <= weighted_2_addr_reg_458_pp0_iter5_reg;
        weighted_2_addr_reg_458_pp0_iter7_reg <= weighted_2_addr_reg_458_pp0_iter6_reg;
        weighted_2_addr_reg_458_pp0_iter8_reg <= weighted_2_addr_reg_458_pp0_iter7_reg;
        weighted_2_addr_reg_458_pp0_iter9_reg <= weighted_2_addr_reg_458_pp0_iter8_reg;
        weighted_3_addr_reg_464 <= zext_ln160_2_fu_359_p1;
        weighted_3_addr_reg_464_pp0_iter10_reg <= weighted_3_addr_reg_464_pp0_iter9_reg;
        weighted_3_addr_reg_464_pp0_iter5_reg <= weighted_3_addr_reg_464;
        weighted_3_addr_reg_464_pp0_iter6_reg <= weighted_3_addr_reg_464_pp0_iter5_reg;
        weighted_3_addr_reg_464_pp0_iter7_reg <= weighted_3_addr_reg_464_pp0_iter6_reg;
        weighted_3_addr_reg_464_pp0_iter8_reg <= weighted_3_addr_reg_464_pp0_iter7_reg;
        weighted_3_addr_reg_464_pp0_iter9_reg <= weighted_3_addr_reg_464_pp0_iter8_reg;
        weighted_addr_reg_446 <= zext_ln160_2_fu_359_p1;
        weighted_addr_reg_446_pp0_iter10_reg <= weighted_addr_reg_446_pp0_iter9_reg;
        weighted_addr_reg_446_pp0_iter5_reg <= weighted_addr_reg_446;
        weighted_addr_reg_446_pp0_iter6_reg <= weighted_addr_reg_446_pp0_iter5_reg;
        weighted_addr_reg_446_pp0_iter7_reg <= weighted_addr_reg_446_pp0_iter6_reg;
        weighted_addr_reg_446_pp0_iter8_reg <= weighted_addr_reg_446_pp0_iter7_reg;
        weighted_addr_reg_446_pp0_iter9_reg <= weighted_addr_reg_446_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        weighted_1_load_reg_485 <= weighted_1_q1;
        weighted_2_load_reg_495 <= weighted_2_q1;
        weighted_3_load_reg_505 <= weighted_3_q1;
        weighted_load_reg_475 <= weighted_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Vbuf_1_ce0 = 1'b1;
    end else begin
        Vbuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Vbuf_2_ce0 = 1'b1;
    end else begin
        Vbuf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Vbuf_3_ce0 = 1'b1;
    end else begin
        Vbuf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Vbuf_ce0 = 1'b1;
    end else begin
        Vbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_252_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter10_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_2 = 6'd0;
    end else begin
        ap_sig_allocacmp_x_2 = x_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        weighted_1_ce0 = 1'b1;
    end else begin
        weighted_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_1_ce1 = 1'b1;
    end else begin
        weighted_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln162_1_reg_414_pp0_iter10_reg == 1'd1))) begin
        weighted_1_we0 = 1'b1;
    end else begin
        weighted_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        weighted_2_ce0 = 1'b1;
    end else begin
        weighted_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_2_ce1 = 1'b1;
    end else begin
        weighted_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln162_2_reg_418_pp0_iter10_reg == 1'd1))) begin
        weighted_2_we0 = 1'b1;
    end else begin
        weighted_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        weighted_3_ce0 = 1'b1;
    end else begin
        weighted_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_3_ce1 = 1'b1;
    end else begin
        weighted_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln162_3_reg_422_pp0_iter10_reg == 1'd1))) begin
        weighted_3_we0 = 1'b1;
    end else begin
        weighted_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        weighted_ce0 = 1'b1;
    end else begin
        weighted_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_ce1 = 1'b1;
    end else begin
        weighted_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln162_reg_410_pp0_iter10_reg == 1'd1))) begin
        weighted_we0 = 1'b1;
    end else begin
        weighted_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Vbuf_1_address0 = zext_ln162_2_fu_296_p1;

assign Vbuf_2_address0 = zext_ln162_2_fu_296_p1;

assign Vbuf_3_address0 = zext_ln162_2_fu_296_p1;

assign Vbuf_address0 = zext_ln162_2_fu_296_p1;

assign add_ln160_fu_348_p2 = (ap_sig_allocacmp_x_2 + 6'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_2294_p_ce = 1'b1;

assign grp_fu_2294_p_din0 = weighted_load_reg_475;

assign grp_fu_2294_p_din1 = mul2_reg_470;

assign grp_fu_2294_p_opcode = 2'd0;

assign grp_fu_2298_p_ce = 1'b1;

assign grp_fu_2298_p_din0 = weighted_1_load_reg_485;

assign grp_fu_2298_p_din1 = mul202_1_reg_480;

assign grp_fu_2298_p_opcode = 2'd0;

assign grp_fu_2302_p_ce = 1'b1;

assign grp_fu_2302_p_din0 = weighted_2_load_reg_495;

assign grp_fu_2302_p_din1 = mul202_2_reg_490;

assign grp_fu_2302_p_opcode = 2'd0;

assign grp_fu_2306_p_ce = 1'b1;

assign grp_fu_2306_p_din0 = weighted_3_load_reg_505;

assign grp_fu_2306_p_din1 = mul202_3_reg_500;

assign grp_fu_2306_p_opcode = 2'd0;

assign grp_fu_2310_p_ce = 1'b1;

assign grp_fu_2310_p_din0 = e;

assign grp_fu_2310_p_din1 = Vbuf_1_load_reg_431;

assign grp_fu_2314_p_ce = 1'b1;

assign grp_fu_2314_p_din0 = e;

assign grp_fu_2314_p_din1 = Vbuf_2_load_reg_436;

assign grp_fu_2318_p_ce = 1'b1;

assign grp_fu_2318_p_din0 = e;

assign grp_fu_2318_p_din1 = Vbuf_3_load_reg_441;

assign grp_fu_936_p_ce = 1'b1;

assign grp_fu_936_p_din0 = e;

assign grp_fu_936_p_din1 = Vbuf_load_reg_426;

assign icmp_ln162_1_fu_310_p2 = (($signed(zext_ln160_1_fu_274_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln162_2_fu_326_p2 = (($signed(zext_ln162_fu_322_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln162_3_fu_342_p2 = (($signed(zext_ln162_1_fu_338_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_304_p2 = (($signed(zext_ln160_fu_264_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign lshr_ln4_fu_278_p4 = {{ap_sig_allocacmp_x_2[4:2]}};

assign or_ln160_1_fu_316_p2 = (trunc_ln160_fu_260_p1 | 5'd2);

assign or_ln160_2_fu_332_p2 = (trunc_ln160_fu_260_p1 | 5'd3);

assign or_ln160_fu_268_p2 = (trunc_ln160_fu_260_p1 | 5'd1);

assign tmp_fu_252_p3 = ap_sig_allocacmp_x_2[32'd5];

assign tmp_s_fu_288_p3 = {{j_3}, {lshr_ln4_fu_278_p4}};

assign trunc_ln160_fu_260_p1 = ap_sig_allocacmp_x_2[4:0];

assign weighted_1_address0 = weighted_1_addr_reg_452_pp0_iter10_reg;

assign weighted_1_address1 = zext_ln160_2_fu_359_p1;

assign weighted_1_d0 = add205_1_reg_515;

assign weighted_2_address0 = weighted_2_addr_reg_458_pp0_iter10_reg;

assign weighted_2_address1 = zext_ln160_2_fu_359_p1;

assign weighted_2_d0 = add205_2_reg_520;

assign weighted_3_address0 = weighted_3_addr_reg_464_pp0_iter10_reg;

assign weighted_3_address1 = zext_ln160_2_fu_359_p1;

assign weighted_3_d0 = add205_3_reg_525;

assign weighted_address0 = weighted_addr_reg_446_pp0_iter10_reg;

assign weighted_address1 = zext_ln160_2_fu_359_p1;

assign weighted_d0 = add_reg_510;

assign zext_ln160_1_fu_274_p1 = or_ln160_fu_268_p2;

assign zext_ln160_2_fu_359_p1 = lshr_ln4_reg_385_pp0_iter3_reg;

assign zext_ln160_fu_264_p1 = ap_sig_allocacmp_x_2;

assign zext_ln162_1_fu_338_p1 = or_ln160_2_fu_332_p2;

assign zext_ln162_2_fu_296_p1 = tmp_s_fu_288_p3;

assign zext_ln162_fu_322_p1 = or_ln160_1_fu_316_p2;

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_VITIS_LOOP_160_4
