-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_hls_flash_attention_hls_Pipeline_LOAD_Q_VITIS_LOOP_69_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln68 : IN STD_LOGIC_VECTOR (62 downto 0);
    Qbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Qbuf_ce0 : OUT STD_LOGIC;
    Qbuf_we0 : OUT STD_LOGIC;
    Qbuf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Qbuf_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Qbuf_1_ce0 : OUT STD_LOGIC;
    Qbuf_1_we0 : OUT STD_LOGIC;
    Qbuf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Qbuf_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Qbuf_2_ce0 : OUT STD_LOGIC;
    Qbuf_2_we0 : OUT STD_LOGIC;
    Qbuf_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Qbuf_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    Qbuf_3_ce0 : OUT STD_LOGIC;
    Qbuf_3_we0 : OUT STD_LOGIC;
    Qbuf_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    zext_ln63 : IN STD_LOGIC_VECTOR (30 downto 0);
    shl_ln68_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    Q : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of flash_attention_hls_flash_attention_hls_Pipeline_LOAD_Q_VITIS_LOOP_69_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv63_1 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln68_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_reg_469_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln68_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal first_iter_0_reg_205 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln63_cast_fu_217_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_cast_reg_460 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln68_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln68_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln68_1_fu_303_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln68_1_reg_473 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln69_fu_315_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln69_reg_478_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln71_fu_329_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln71_reg_482_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal gmem0_addr_reg_487 : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem0_addr_read_reg_493 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_first_iter_0_phi_fu_209_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln71_fu_405_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln69_fu_395_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_100 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln69_fu_335_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_fu_104 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal select_ln68_1_fu_291_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal indvar_flatten_fu_108 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln68_3_fu_256_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal bitcast_ln71_fu_412_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln69_fu_242_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln69_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln68_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln68_2_fu_265_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln68_fu_299_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln68_fu_283_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_s_fu_307_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln_fu_319_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_356_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln68_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln68_1_fu_368_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln68_fu_376_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln68_1_fu_380_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln2_fu_385_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component flash_attention_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_0_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln68_reg_465 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_0_reg_205 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_0_reg_205 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    i_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_104 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln68_fu_251_p2 = ap_const_lv1_0))) then 
                    i_fu_104 <= select_ln68_1_fu_291_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_108 <= ap_const_lv63_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln68_fu_251_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_108 <= add_ln68_3_fu_256_p2;
                end if;
            end if; 
        end if;
    end process;

    x_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_100 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln68_fu_251_p2 = ap_const_lv1_0))) then 
                    x_fu_100 <= add_ln69_fu_335_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln71_reg_482 <= add_ln71_fu_329_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln68_reg_465 <= icmp_ln68_fu_251_p2;
                or_ln68_reg_469 <= or_ln68_fu_277_p2;
                trunc_ln68_1_reg_473 <= trunc_ln68_1_fu_303_p1;
                trunc_ln69_reg_478 <= trunc_ln69_fu_315_p1;
                    zext_ln63_cast_reg_460(30 downto 0) <= zext_ln63_cast_fu_217_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln71_reg_482_pp0_iter10_reg <= add_ln71_reg_482_pp0_iter9_reg;
                add_ln71_reg_482_pp0_iter11_reg <= add_ln71_reg_482_pp0_iter10_reg;
                add_ln71_reg_482_pp0_iter2_reg <= add_ln71_reg_482;
                add_ln71_reg_482_pp0_iter3_reg <= add_ln71_reg_482_pp0_iter2_reg;
                add_ln71_reg_482_pp0_iter4_reg <= add_ln71_reg_482_pp0_iter3_reg;
                add_ln71_reg_482_pp0_iter5_reg <= add_ln71_reg_482_pp0_iter4_reg;
                add_ln71_reg_482_pp0_iter6_reg <= add_ln71_reg_482_pp0_iter5_reg;
                add_ln71_reg_482_pp0_iter7_reg <= add_ln71_reg_482_pp0_iter6_reg;
                add_ln71_reg_482_pp0_iter8_reg <= add_ln71_reg_482_pp0_iter7_reg;
                add_ln71_reg_482_pp0_iter9_reg <= add_ln71_reg_482_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem0_addr_read_reg_493 <= m_axi_gmem0_RDATA;
                gmem0_addr_reg_487 <= sext_ln69_fu_395_p1;
                or_ln68_reg_469_pp0_iter2_reg <= or_ln68_reg_469;
                trunc_ln69_reg_478_pp0_iter10_reg <= trunc_ln69_reg_478_pp0_iter9_reg;
                trunc_ln69_reg_478_pp0_iter11_reg <= trunc_ln69_reg_478_pp0_iter10_reg;
                trunc_ln69_reg_478_pp0_iter2_reg <= trunc_ln69_reg_478;
                trunc_ln69_reg_478_pp0_iter3_reg <= trunc_ln69_reg_478_pp0_iter2_reg;
                trunc_ln69_reg_478_pp0_iter4_reg <= trunc_ln69_reg_478_pp0_iter3_reg;
                trunc_ln69_reg_478_pp0_iter5_reg <= trunc_ln69_reg_478_pp0_iter4_reg;
                trunc_ln69_reg_478_pp0_iter6_reg <= trunc_ln69_reg_478_pp0_iter5_reg;
                trunc_ln69_reg_478_pp0_iter7_reg <= trunc_ln69_reg_478_pp0_iter6_reg;
                trunc_ln69_reg_478_pp0_iter8_reg <= trunc_ln69_reg_478_pp0_iter7_reg;
                trunc_ln69_reg_478_pp0_iter9_reg <= trunc_ln69_reg_478_pp0_iter8_reg;
            end if;
        end if;
    end process;
    zext_ln63_cast_reg_460(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Qbuf_1_address0 <= zext_ln71_fu_405_p1(6 - 1 downto 0);

    Qbuf_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_1_ce0 <= ap_const_logic_1;
        else 
            Qbuf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_1_d0 <= bitcast_ln71_fu_412_p1;

    Qbuf_1_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln69_reg_478_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln69_reg_478_pp0_iter11_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_1_we0 <= ap_const_logic_1;
        else 
            Qbuf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_2_address0 <= zext_ln71_fu_405_p1(6 - 1 downto 0);

    Qbuf_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_2_ce0 <= ap_const_logic_1;
        else 
            Qbuf_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_2_d0 <= bitcast_ln71_fu_412_p1;

    Qbuf_2_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln69_reg_478_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln69_reg_478_pp0_iter11_reg = ap_const_lv2_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_2_we0 <= ap_const_logic_1;
        else 
            Qbuf_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_3_address0 <= zext_ln71_fu_405_p1(6 - 1 downto 0);

    Qbuf_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_3_ce0 <= ap_const_logic_1;
        else 
            Qbuf_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_3_d0 <= bitcast_ln71_fu_412_p1;

    Qbuf_3_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln69_reg_478_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln69_reg_478_pp0_iter11_reg = ap_const_lv2_3) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_3_we0 <= ap_const_logic_1;
        else 
            Qbuf_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_address0 <= zext_ln71_fu_405_p1(6 - 1 downto 0);

    Qbuf_ce0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_ce0 <= ap_const_logic_1;
        else 
            Qbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Qbuf_d0 <= bitcast_ln71_fu_412_p1;

    Qbuf_we0_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001, trunc_ln69_reg_478_pp0_iter11_reg)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (trunc_ln69_reg_478_pp0_iter11_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            Qbuf_we0 <= ap_const_logic_1;
        else 
            Qbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln68_1_fu_380_p2 <= std_logic_vector(signed(sext_ln68_fu_376_p1) + signed(Q));
    add_ln68_2_fu_265_p2 <= std_logic_vector(unsigned(i_fu_104) + unsigned(ap_const_lv31_1));
    add_ln68_3_fu_256_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_108) + unsigned(ap_const_lv63_1));
    add_ln68_fu_363_p2 <= std_logic_vector(unsigned(shl_ln_fu_356_p3) + unsigned(shl_ln68_2));
    add_ln69_fu_335_p2 <= std_logic_vector(unsigned(select_ln68_fu_283_p3) + unsigned(ap_const_lv31_1));
    add_ln71_fu_329_p2 <= std_logic_vector(unsigned(tmp_s_fu_307_p3) + unsigned(lshr_ln_fu_319_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, ap_block_state4_io, ap_block_state12_pp0_stage0_iter11)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage0_iter11)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, ap_block_state4_io, ap_block_state12_pp0_stage0_iter11)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state12_pp0_stage0_iter11)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_state12_pp0_stage0_iter11_assign_proc : process(m_axi_gmem0_RVALID)
    begin
                ap_block_state12_pp0_stage0_iter11 <= (m_axi_gmem0_RVALID = ap_const_logic_0);
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem0_ARREADY, or_ln68_reg_469_pp0_iter2_reg)
    begin
                ap_block_state4_io <= ((m_axi_gmem0_ARREADY = ap_const_logic_0) and (or_ln68_reg_469_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln68_fu_251_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln68_fu_251_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_0_phi_fu_209_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, first_iter_0_reg_205, icmp_ln68_reg_465)
    begin
        if (((icmp_ln68_reg_465 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_0_phi_fu_209_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_0_phi_fu_209_p4 <= first_iter_0_reg_205;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln71_fu_412_p1 <= gmem0_addr_read_reg_493;

    gmem0_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_ARREADY, or_ln68_reg_469_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln68_reg_469_pp0_iter2_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln68_fu_251_p2 <= "1" when (indvar_flatten_fu_108 = mul_ln68) else "0";
    icmp_ln69_fu_246_p2 <= "1" when (signed(zext_ln69_fu_242_p1) < signed(d)) else "0";
    lshr_ln_fu_319_p4 <= select_ln68_fu_283_p3(7 downto 2);
    m_axi_gmem0_ARADDR <= gmem0_addr_reg_487;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= zext_ln63_cast_reg_460;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter3, or_ln68_reg_469_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln68_reg_469_pp0_iter2_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv32_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    or_ln68_fu_277_p2 <= (xor_ln68_fu_271_p2 or ap_phi_mux_first_iter_0_phi_fu_209_p4);
    select_ln68_1_fu_291_p3 <= 
        i_fu_104 when (icmp_ln69_fu_246_p2(0) = '1') else 
        add_ln68_2_fu_265_p2;
    select_ln68_fu_283_p3 <= 
        x_fu_100 when (icmp_ln69_fu_246_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln68_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln68_1_fu_368_p3),64));

        sext_ln69_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln2_fu_385_p4),64));

    shl_ln68_1_fu_368_p3 <= (add_ln68_fu_363_p2 & ap_const_lv2_0);
    shl_ln_fu_356_p3 <= (trunc_ln68_1_reg_473 & ap_const_lv5_0);
    tmp_s_fu_307_p3 <= (trunc_ln68_fu_299_p1 & ap_const_lv3_0);
    trunc_ln2_fu_385_p4 <= add_ln68_1_fu_380_p2(63 downto 2);
    trunc_ln68_1_fu_303_p1 <= select_ln68_1_fu_291_p3(27 - 1 downto 0);
    trunc_ln68_fu_299_p1 <= select_ln68_1_fu_291_p3(3 - 1 downto 0);
    trunc_ln69_fu_315_p1 <= select_ln68_fu_283_p3(2 - 1 downto 0);
    xor_ln68_fu_271_p2 <= (icmp_ln69_fu_246_p2 xor ap_const_lv1_1);
    zext_ln63_cast_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln63),32));
    zext_ln69_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_100),32));
    zext_ln71_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln71_reg_482_pp0_iter11_reg),64));
end behav;
