-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_hls_flash_attention_hls_Pipeline_UPDATE_ACC is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    i_4 : IN STD_LOGIC_VECTOR (2 downto 0);
    acc_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_ce0 : OUT STD_LOGIC;
    acc_we0 : OUT STD_LOGIC;
    acc_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_ce1 : OUT STD_LOGIC;
    acc_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_1_ce0 : OUT STD_LOGIC;
    acc_1_we0 : OUT STD_LOGIC;
    acc_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_1_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_1_ce1 : OUT STD_LOGIC;
    acc_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_2_ce0 : OUT STD_LOGIC;
    acc_2_we0 : OUT STD_LOGIC;
    acc_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_2_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_2_ce1 : OUT STD_LOGIC;
    acc_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_3_ce0 : OUT STD_LOGIC;
    acc_3_we0 : OUT STD_LOGIC;
    acc_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_3_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_3_ce1 : OUT STD_LOGIC;
    acc_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weighted_ce0 : OUT STD_LOGIC;
    weighted_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    l_new : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weighted_1_ce0 : OUT STD_LOGIC;
    weighted_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weighted_2_ce0 : OUT STD_LOGIC;
    weighted_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weighted_3_ce0 : OUT STD_LOGIC;
    weighted_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2294_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2294_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2294_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_2294_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2294_p_ce : OUT STD_LOGIC;
    grp_fu_2298_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2298_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2298_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_2298_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2298_p_ce : OUT STD_LOGIC;
    grp_fu_2302_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2302_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2302_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_2302_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2302_p_ce : OUT STD_LOGIC;
    grp_fu_2306_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2306_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2306_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_2306_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2306_p_ce : OUT STD_LOGIC;
    grp_fu_936_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_936_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_936_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_936_p_ce : OUT STD_LOGIC;
    grp_fu_2310_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2310_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2310_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2310_p_ce : OUT STD_LOGIC;
    grp_fu_2314_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2314_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2314_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2314_p_ce : OUT STD_LOGIC;
    grp_fu_2318_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2318_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2318_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_2318_p_ce : OUT STD_LOGIC;
    grp_fu_940_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_940_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_940_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_940_p_ce : OUT STD_LOGIC );
end;


architecture behav of flash_attention_hls_flash_attention_hls_Pipeline_UPDATE_ACC is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_276_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal lshr_ln5_fu_302_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln5_reg_417 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln5_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln5_reg_417_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln5_reg_417_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_addr_reg_422 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_addr_reg_422_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_1_addr_reg_428_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_2_addr_reg_434_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter15_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter16_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter17_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter18_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter19_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter20_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter21_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter22_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter23_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter24_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter25_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_3_addr_reg_440_pp0_iter26_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln174_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_reg_446_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_1_reg_450_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_2_reg_454_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln174_3_reg_458_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_load_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_load_reg_467 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_2_load_reg_472 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_3_load_reg_477 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul3_reg_502 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_load_reg_507 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul231_1_reg_512 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_1_load_reg_517 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul231_2_reg_522 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_2_load_reg_527 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul231_3_reg_532 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_3_load_reg_537 : STD_LOGIC_VECTOR (31 downto 0);
    signal add1_reg_542 : STD_LOGIC_VECTOR (31 downto 0);
    signal add234_1_reg_547 : STD_LOGIC_VECTOR (31 downto 0);
    signal add234_2_reg_552 : STD_LOGIC_VECTOR (31 downto 0);
    signal add234_3_reg_557 : STD_LOGIC_VECTOR (31 downto 0);
    signal div_reg_562 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div235_1_reg_567 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_260_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div235_2_reg_572 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div235_3_reg_577 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln176_fu_320_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln172_2_fu_383_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_72 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln172_fu_372_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln172_fu_284_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln172_fu_292_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_312_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln172_fu_288_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln172_1_fu_298_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln172_1_fu_340_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln174_fu_346_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln172_2_fu_356_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln174_1_fu_362_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter23_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter24_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter25_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter26_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_hls_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_hls_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fdiv_32ns_32ns_32_16_no_dsp_1_U180 : component flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add234_1_reg_547,
        din1 => l_new,
        ce => ap_const_logic_1,
        dout => grp_fu_256_p2);

    fdiv_32ns_32ns_32_16_no_dsp_1_U181 : component flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add234_2_reg_552,
        din1 => l_new,
        ce => ap_const_logic_1,
        dout => grp_fu_260_p2);

    fdiv_32ns_32ns_32_16_no_dsp_1_U182 : component flash_attention_hls_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add234_3_reg_557,
        din1 => l_new,
        ce => ap_const_logic_1,
        dout => grp_fu_264_p2);

    flow_control_loop_pipe_sequential_init_U : component flash_attention_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    x_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_fu_276_p3 = ap_const_lv1_0))) then 
                    x_fu_72 <= add_ln172_fu_372_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_72 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_1_addr_reg_428 <= zext_ln176_fu_320_p1(6 - 1 downto 0);
                acc_1_addr_reg_428_pp0_iter1_reg <= acc_1_addr_reg_428;
                acc_2_addr_reg_434 <= zext_ln176_fu_320_p1(6 - 1 downto 0);
                acc_2_addr_reg_434_pp0_iter1_reg <= acc_2_addr_reg_434;
                acc_3_addr_reg_440 <= zext_ln176_fu_320_p1(6 - 1 downto 0);
                acc_3_addr_reg_440_pp0_iter1_reg <= acc_3_addr_reg_440;
                acc_addr_reg_422 <= zext_ln176_fu_320_p1(6 - 1 downto 0);
                acc_addr_reg_422_pp0_iter1_reg <= acc_addr_reg_422;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln174_1_reg_450 <= icmp_ln174_1_fu_334_p2;
                icmp_ln174_1_reg_450_pp0_iter1_reg <= icmp_ln174_1_reg_450;
                icmp_ln174_2_reg_454 <= icmp_ln174_2_fu_350_p2;
                icmp_ln174_2_reg_454_pp0_iter1_reg <= icmp_ln174_2_reg_454;
                icmp_ln174_3_reg_458 <= icmp_ln174_3_fu_366_p2;
                icmp_ln174_3_reg_458_pp0_iter1_reg <= icmp_ln174_3_reg_458;
                icmp_ln174_reg_446 <= icmp_ln174_fu_328_p2;
                icmp_ln174_reg_446_pp0_iter1_reg <= icmp_ln174_reg_446;
                lshr_ln5_reg_417 <= ap_sig_allocacmp_x_3(4 downto 2);
                lshr_ln5_reg_417_pp0_iter1_reg <= lshr_ln5_reg_417;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                acc_1_addr_reg_428_pp0_iter10_reg <= acc_1_addr_reg_428_pp0_iter9_reg;
                acc_1_addr_reg_428_pp0_iter11_reg <= acc_1_addr_reg_428_pp0_iter10_reg;
                acc_1_addr_reg_428_pp0_iter12_reg <= acc_1_addr_reg_428_pp0_iter11_reg;
                acc_1_addr_reg_428_pp0_iter13_reg <= acc_1_addr_reg_428_pp0_iter12_reg;
                acc_1_addr_reg_428_pp0_iter14_reg <= acc_1_addr_reg_428_pp0_iter13_reg;
                acc_1_addr_reg_428_pp0_iter15_reg <= acc_1_addr_reg_428_pp0_iter14_reg;
                acc_1_addr_reg_428_pp0_iter16_reg <= acc_1_addr_reg_428_pp0_iter15_reg;
                acc_1_addr_reg_428_pp0_iter17_reg <= acc_1_addr_reg_428_pp0_iter16_reg;
                acc_1_addr_reg_428_pp0_iter18_reg <= acc_1_addr_reg_428_pp0_iter17_reg;
                acc_1_addr_reg_428_pp0_iter19_reg <= acc_1_addr_reg_428_pp0_iter18_reg;
                acc_1_addr_reg_428_pp0_iter20_reg <= acc_1_addr_reg_428_pp0_iter19_reg;
                acc_1_addr_reg_428_pp0_iter21_reg <= acc_1_addr_reg_428_pp0_iter20_reg;
                acc_1_addr_reg_428_pp0_iter22_reg <= acc_1_addr_reg_428_pp0_iter21_reg;
                acc_1_addr_reg_428_pp0_iter23_reg <= acc_1_addr_reg_428_pp0_iter22_reg;
                acc_1_addr_reg_428_pp0_iter24_reg <= acc_1_addr_reg_428_pp0_iter23_reg;
                acc_1_addr_reg_428_pp0_iter25_reg <= acc_1_addr_reg_428_pp0_iter24_reg;
                acc_1_addr_reg_428_pp0_iter26_reg <= acc_1_addr_reg_428_pp0_iter25_reg;
                acc_1_addr_reg_428_pp0_iter2_reg <= acc_1_addr_reg_428_pp0_iter1_reg;
                acc_1_addr_reg_428_pp0_iter3_reg <= acc_1_addr_reg_428_pp0_iter2_reg;
                acc_1_addr_reg_428_pp0_iter4_reg <= acc_1_addr_reg_428_pp0_iter3_reg;
                acc_1_addr_reg_428_pp0_iter5_reg <= acc_1_addr_reg_428_pp0_iter4_reg;
                acc_1_addr_reg_428_pp0_iter6_reg <= acc_1_addr_reg_428_pp0_iter5_reg;
                acc_1_addr_reg_428_pp0_iter7_reg <= acc_1_addr_reg_428_pp0_iter6_reg;
                acc_1_addr_reg_428_pp0_iter8_reg <= acc_1_addr_reg_428_pp0_iter7_reg;
                acc_1_addr_reg_428_pp0_iter9_reg <= acc_1_addr_reg_428_pp0_iter8_reg;
                acc_2_addr_reg_434_pp0_iter10_reg <= acc_2_addr_reg_434_pp0_iter9_reg;
                acc_2_addr_reg_434_pp0_iter11_reg <= acc_2_addr_reg_434_pp0_iter10_reg;
                acc_2_addr_reg_434_pp0_iter12_reg <= acc_2_addr_reg_434_pp0_iter11_reg;
                acc_2_addr_reg_434_pp0_iter13_reg <= acc_2_addr_reg_434_pp0_iter12_reg;
                acc_2_addr_reg_434_pp0_iter14_reg <= acc_2_addr_reg_434_pp0_iter13_reg;
                acc_2_addr_reg_434_pp0_iter15_reg <= acc_2_addr_reg_434_pp0_iter14_reg;
                acc_2_addr_reg_434_pp0_iter16_reg <= acc_2_addr_reg_434_pp0_iter15_reg;
                acc_2_addr_reg_434_pp0_iter17_reg <= acc_2_addr_reg_434_pp0_iter16_reg;
                acc_2_addr_reg_434_pp0_iter18_reg <= acc_2_addr_reg_434_pp0_iter17_reg;
                acc_2_addr_reg_434_pp0_iter19_reg <= acc_2_addr_reg_434_pp0_iter18_reg;
                acc_2_addr_reg_434_pp0_iter20_reg <= acc_2_addr_reg_434_pp0_iter19_reg;
                acc_2_addr_reg_434_pp0_iter21_reg <= acc_2_addr_reg_434_pp0_iter20_reg;
                acc_2_addr_reg_434_pp0_iter22_reg <= acc_2_addr_reg_434_pp0_iter21_reg;
                acc_2_addr_reg_434_pp0_iter23_reg <= acc_2_addr_reg_434_pp0_iter22_reg;
                acc_2_addr_reg_434_pp0_iter24_reg <= acc_2_addr_reg_434_pp0_iter23_reg;
                acc_2_addr_reg_434_pp0_iter25_reg <= acc_2_addr_reg_434_pp0_iter24_reg;
                acc_2_addr_reg_434_pp0_iter26_reg <= acc_2_addr_reg_434_pp0_iter25_reg;
                acc_2_addr_reg_434_pp0_iter2_reg <= acc_2_addr_reg_434_pp0_iter1_reg;
                acc_2_addr_reg_434_pp0_iter3_reg <= acc_2_addr_reg_434_pp0_iter2_reg;
                acc_2_addr_reg_434_pp0_iter4_reg <= acc_2_addr_reg_434_pp0_iter3_reg;
                acc_2_addr_reg_434_pp0_iter5_reg <= acc_2_addr_reg_434_pp0_iter4_reg;
                acc_2_addr_reg_434_pp0_iter6_reg <= acc_2_addr_reg_434_pp0_iter5_reg;
                acc_2_addr_reg_434_pp0_iter7_reg <= acc_2_addr_reg_434_pp0_iter6_reg;
                acc_2_addr_reg_434_pp0_iter8_reg <= acc_2_addr_reg_434_pp0_iter7_reg;
                acc_2_addr_reg_434_pp0_iter9_reg <= acc_2_addr_reg_434_pp0_iter8_reg;
                acc_3_addr_reg_440_pp0_iter10_reg <= acc_3_addr_reg_440_pp0_iter9_reg;
                acc_3_addr_reg_440_pp0_iter11_reg <= acc_3_addr_reg_440_pp0_iter10_reg;
                acc_3_addr_reg_440_pp0_iter12_reg <= acc_3_addr_reg_440_pp0_iter11_reg;
                acc_3_addr_reg_440_pp0_iter13_reg <= acc_3_addr_reg_440_pp0_iter12_reg;
                acc_3_addr_reg_440_pp0_iter14_reg <= acc_3_addr_reg_440_pp0_iter13_reg;
                acc_3_addr_reg_440_pp0_iter15_reg <= acc_3_addr_reg_440_pp0_iter14_reg;
                acc_3_addr_reg_440_pp0_iter16_reg <= acc_3_addr_reg_440_pp0_iter15_reg;
                acc_3_addr_reg_440_pp0_iter17_reg <= acc_3_addr_reg_440_pp0_iter16_reg;
                acc_3_addr_reg_440_pp0_iter18_reg <= acc_3_addr_reg_440_pp0_iter17_reg;
                acc_3_addr_reg_440_pp0_iter19_reg <= acc_3_addr_reg_440_pp0_iter18_reg;
                acc_3_addr_reg_440_pp0_iter20_reg <= acc_3_addr_reg_440_pp0_iter19_reg;
                acc_3_addr_reg_440_pp0_iter21_reg <= acc_3_addr_reg_440_pp0_iter20_reg;
                acc_3_addr_reg_440_pp0_iter22_reg <= acc_3_addr_reg_440_pp0_iter21_reg;
                acc_3_addr_reg_440_pp0_iter23_reg <= acc_3_addr_reg_440_pp0_iter22_reg;
                acc_3_addr_reg_440_pp0_iter24_reg <= acc_3_addr_reg_440_pp0_iter23_reg;
                acc_3_addr_reg_440_pp0_iter25_reg <= acc_3_addr_reg_440_pp0_iter24_reg;
                acc_3_addr_reg_440_pp0_iter26_reg <= acc_3_addr_reg_440_pp0_iter25_reg;
                acc_3_addr_reg_440_pp0_iter2_reg <= acc_3_addr_reg_440_pp0_iter1_reg;
                acc_3_addr_reg_440_pp0_iter3_reg <= acc_3_addr_reg_440_pp0_iter2_reg;
                acc_3_addr_reg_440_pp0_iter4_reg <= acc_3_addr_reg_440_pp0_iter3_reg;
                acc_3_addr_reg_440_pp0_iter5_reg <= acc_3_addr_reg_440_pp0_iter4_reg;
                acc_3_addr_reg_440_pp0_iter6_reg <= acc_3_addr_reg_440_pp0_iter5_reg;
                acc_3_addr_reg_440_pp0_iter7_reg <= acc_3_addr_reg_440_pp0_iter6_reg;
                acc_3_addr_reg_440_pp0_iter8_reg <= acc_3_addr_reg_440_pp0_iter7_reg;
                acc_3_addr_reg_440_pp0_iter9_reg <= acc_3_addr_reg_440_pp0_iter8_reg;
                acc_addr_reg_422_pp0_iter10_reg <= acc_addr_reg_422_pp0_iter9_reg;
                acc_addr_reg_422_pp0_iter11_reg <= acc_addr_reg_422_pp0_iter10_reg;
                acc_addr_reg_422_pp0_iter12_reg <= acc_addr_reg_422_pp0_iter11_reg;
                acc_addr_reg_422_pp0_iter13_reg <= acc_addr_reg_422_pp0_iter12_reg;
                acc_addr_reg_422_pp0_iter14_reg <= acc_addr_reg_422_pp0_iter13_reg;
                acc_addr_reg_422_pp0_iter15_reg <= acc_addr_reg_422_pp0_iter14_reg;
                acc_addr_reg_422_pp0_iter16_reg <= acc_addr_reg_422_pp0_iter15_reg;
                acc_addr_reg_422_pp0_iter17_reg <= acc_addr_reg_422_pp0_iter16_reg;
                acc_addr_reg_422_pp0_iter18_reg <= acc_addr_reg_422_pp0_iter17_reg;
                acc_addr_reg_422_pp0_iter19_reg <= acc_addr_reg_422_pp0_iter18_reg;
                acc_addr_reg_422_pp0_iter20_reg <= acc_addr_reg_422_pp0_iter19_reg;
                acc_addr_reg_422_pp0_iter21_reg <= acc_addr_reg_422_pp0_iter20_reg;
                acc_addr_reg_422_pp0_iter22_reg <= acc_addr_reg_422_pp0_iter21_reg;
                acc_addr_reg_422_pp0_iter23_reg <= acc_addr_reg_422_pp0_iter22_reg;
                acc_addr_reg_422_pp0_iter24_reg <= acc_addr_reg_422_pp0_iter23_reg;
                acc_addr_reg_422_pp0_iter25_reg <= acc_addr_reg_422_pp0_iter24_reg;
                acc_addr_reg_422_pp0_iter26_reg <= acc_addr_reg_422_pp0_iter25_reg;
                acc_addr_reg_422_pp0_iter2_reg <= acc_addr_reg_422_pp0_iter1_reg;
                acc_addr_reg_422_pp0_iter3_reg <= acc_addr_reg_422_pp0_iter2_reg;
                acc_addr_reg_422_pp0_iter4_reg <= acc_addr_reg_422_pp0_iter3_reg;
                acc_addr_reg_422_pp0_iter5_reg <= acc_addr_reg_422_pp0_iter4_reg;
                acc_addr_reg_422_pp0_iter6_reg <= acc_addr_reg_422_pp0_iter5_reg;
                acc_addr_reg_422_pp0_iter7_reg <= acc_addr_reg_422_pp0_iter6_reg;
                acc_addr_reg_422_pp0_iter8_reg <= acc_addr_reg_422_pp0_iter7_reg;
                acc_addr_reg_422_pp0_iter9_reg <= acc_addr_reg_422_pp0_iter8_reg;
                add1_reg_542 <= grp_fu_2294_p_dout0;
                add234_1_reg_547 <= grp_fu_2298_p_dout0;
                add234_2_reg_552 <= grp_fu_2302_p_dout0;
                add234_3_reg_557 <= grp_fu_2306_p_dout0;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
                ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
                ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
                ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                div235_1_reg_567 <= grp_fu_256_p2;
                div235_2_reg_572 <= grp_fu_260_p2;
                div235_3_reg_577 <= grp_fu_264_p2;
                div_reg_562 <= grp_fu_940_p_dout0;
                icmp_ln174_1_reg_450_pp0_iter10_reg <= icmp_ln174_1_reg_450_pp0_iter9_reg;
                icmp_ln174_1_reg_450_pp0_iter11_reg <= icmp_ln174_1_reg_450_pp0_iter10_reg;
                icmp_ln174_1_reg_450_pp0_iter12_reg <= icmp_ln174_1_reg_450_pp0_iter11_reg;
                icmp_ln174_1_reg_450_pp0_iter13_reg <= icmp_ln174_1_reg_450_pp0_iter12_reg;
                icmp_ln174_1_reg_450_pp0_iter14_reg <= icmp_ln174_1_reg_450_pp0_iter13_reg;
                icmp_ln174_1_reg_450_pp0_iter15_reg <= icmp_ln174_1_reg_450_pp0_iter14_reg;
                icmp_ln174_1_reg_450_pp0_iter16_reg <= icmp_ln174_1_reg_450_pp0_iter15_reg;
                icmp_ln174_1_reg_450_pp0_iter17_reg <= icmp_ln174_1_reg_450_pp0_iter16_reg;
                icmp_ln174_1_reg_450_pp0_iter18_reg <= icmp_ln174_1_reg_450_pp0_iter17_reg;
                icmp_ln174_1_reg_450_pp0_iter19_reg <= icmp_ln174_1_reg_450_pp0_iter18_reg;
                icmp_ln174_1_reg_450_pp0_iter20_reg <= icmp_ln174_1_reg_450_pp0_iter19_reg;
                icmp_ln174_1_reg_450_pp0_iter21_reg <= icmp_ln174_1_reg_450_pp0_iter20_reg;
                icmp_ln174_1_reg_450_pp0_iter22_reg <= icmp_ln174_1_reg_450_pp0_iter21_reg;
                icmp_ln174_1_reg_450_pp0_iter23_reg <= icmp_ln174_1_reg_450_pp0_iter22_reg;
                icmp_ln174_1_reg_450_pp0_iter24_reg <= icmp_ln174_1_reg_450_pp0_iter23_reg;
                icmp_ln174_1_reg_450_pp0_iter25_reg <= icmp_ln174_1_reg_450_pp0_iter24_reg;
                icmp_ln174_1_reg_450_pp0_iter26_reg <= icmp_ln174_1_reg_450_pp0_iter25_reg;
                icmp_ln174_1_reg_450_pp0_iter2_reg <= icmp_ln174_1_reg_450_pp0_iter1_reg;
                icmp_ln174_1_reg_450_pp0_iter3_reg <= icmp_ln174_1_reg_450_pp0_iter2_reg;
                icmp_ln174_1_reg_450_pp0_iter4_reg <= icmp_ln174_1_reg_450_pp0_iter3_reg;
                icmp_ln174_1_reg_450_pp0_iter5_reg <= icmp_ln174_1_reg_450_pp0_iter4_reg;
                icmp_ln174_1_reg_450_pp0_iter6_reg <= icmp_ln174_1_reg_450_pp0_iter5_reg;
                icmp_ln174_1_reg_450_pp0_iter7_reg <= icmp_ln174_1_reg_450_pp0_iter6_reg;
                icmp_ln174_1_reg_450_pp0_iter8_reg <= icmp_ln174_1_reg_450_pp0_iter7_reg;
                icmp_ln174_1_reg_450_pp0_iter9_reg <= icmp_ln174_1_reg_450_pp0_iter8_reg;
                icmp_ln174_2_reg_454_pp0_iter10_reg <= icmp_ln174_2_reg_454_pp0_iter9_reg;
                icmp_ln174_2_reg_454_pp0_iter11_reg <= icmp_ln174_2_reg_454_pp0_iter10_reg;
                icmp_ln174_2_reg_454_pp0_iter12_reg <= icmp_ln174_2_reg_454_pp0_iter11_reg;
                icmp_ln174_2_reg_454_pp0_iter13_reg <= icmp_ln174_2_reg_454_pp0_iter12_reg;
                icmp_ln174_2_reg_454_pp0_iter14_reg <= icmp_ln174_2_reg_454_pp0_iter13_reg;
                icmp_ln174_2_reg_454_pp0_iter15_reg <= icmp_ln174_2_reg_454_pp0_iter14_reg;
                icmp_ln174_2_reg_454_pp0_iter16_reg <= icmp_ln174_2_reg_454_pp0_iter15_reg;
                icmp_ln174_2_reg_454_pp0_iter17_reg <= icmp_ln174_2_reg_454_pp0_iter16_reg;
                icmp_ln174_2_reg_454_pp0_iter18_reg <= icmp_ln174_2_reg_454_pp0_iter17_reg;
                icmp_ln174_2_reg_454_pp0_iter19_reg <= icmp_ln174_2_reg_454_pp0_iter18_reg;
                icmp_ln174_2_reg_454_pp0_iter20_reg <= icmp_ln174_2_reg_454_pp0_iter19_reg;
                icmp_ln174_2_reg_454_pp0_iter21_reg <= icmp_ln174_2_reg_454_pp0_iter20_reg;
                icmp_ln174_2_reg_454_pp0_iter22_reg <= icmp_ln174_2_reg_454_pp0_iter21_reg;
                icmp_ln174_2_reg_454_pp0_iter23_reg <= icmp_ln174_2_reg_454_pp0_iter22_reg;
                icmp_ln174_2_reg_454_pp0_iter24_reg <= icmp_ln174_2_reg_454_pp0_iter23_reg;
                icmp_ln174_2_reg_454_pp0_iter25_reg <= icmp_ln174_2_reg_454_pp0_iter24_reg;
                icmp_ln174_2_reg_454_pp0_iter26_reg <= icmp_ln174_2_reg_454_pp0_iter25_reg;
                icmp_ln174_2_reg_454_pp0_iter2_reg <= icmp_ln174_2_reg_454_pp0_iter1_reg;
                icmp_ln174_2_reg_454_pp0_iter3_reg <= icmp_ln174_2_reg_454_pp0_iter2_reg;
                icmp_ln174_2_reg_454_pp0_iter4_reg <= icmp_ln174_2_reg_454_pp0_iter3_reg;
                icmp_ln174_2_reg_454_pp0_iter5_reg <= icmp_ln174_2_reg_454_pp0_iter4_reg;
                icmp_ln174_2_reg_454_pp0_iter6_reg <= icmp_ln174_2_reg_454_pp0_iter5_reg;
                icmp_ln174_2_reg_454_pp0_iter7_reg <= icmp_ln174_2_reg_454_pp0_iter6_reg;
                icmp_ln174_2_reg_454_pp0_iter8_reg <= icmp_ln174_2_reg_454_pp0_iter7_reg;
                icmp_ln174_2_reg_454_pp0_iter9_reg <= icmp_ln174_2_reg_454_pp0_iter8_reg;
                icmp_ln174_3_reg_458_pp0_iter10_reg <= icmp_ln174_3_reg_458_pp0_iter9_reg;
                icmp_ln174_3_reg_458_pp0_iter11_reg <= icmp_ln174_3_reg_458_pp0_iter10_reg;
                icmp_ln174_3_reg_458_pp0_iter12_reg <= icmp_ln174_3_reg_458_pp0_iter11_reg;
                icmp_ln174_3_reg_458_pp0_iter13_reg <= icmp_ln174_3_reg_458_pp0_iter12_reg;
                icmp_ln174_3_reg_458_pp0_iter14_reg <= icmp_ln174_3_reg_458_pp0_iter13_reg;
                icmp_ln174_3_reg_458_pp0_iter15_reg <= icmp_ln174_3_reg_458_pp0_iter14_reg;
                icmp_ln174_3_reg_458_pp0_iter16_reg <= icmp_ln174_3_reg_458_pp0_iter15_reg;
                icmp_ln174_3_reg_458_pp0_iter17_reg <= icmp_ln174_3_reg_458_pp0_iter16_reg;
                icmp_ln174_3_reg_458_pp0_iter18_reg <= icmp_ln174_3_reg_458_pp0_iter17_reg;
                icmp_ln174_3_reg_458_pp0_iter19_reg <= icmp_ln174_3_reg_458_pp0_iter18_reg;
                icmp_ln174_3_reg_458_pp0_iter20_reg <= icmp_ln174_3_reg_458_pp0_iter19_reg;
                icmp_ln174_3_reg_458_pp0_iter21_reg <= icmp_ln174_3_reg_458_pp0_iter20_reg;
                icmp_ln174_3_reg_458_pp0_iter22_reg <= icmp_ln174_3_reg_458_pp0_iter21_reg;
                icmp_ln174_3_reg_458_pp0_iter23_reg <= icmp_ln174_3_reg_458_pp0_iter22_reg;
                icmp_ln174_3_reg_458_pp0_iter24_reg <= icmp_ln174_3_reg_458_pp0_iter23_reg;
                icmp_ln174_3_reg_458_pp0_iter25_reg <= icmp_ln174_3_reg_458_pp0_iter24_reg;
                icmp_ln174_3_reg_458_pp0_iter26_reg <= icmp_ln174_3_reg_458_pp0_iter25_reg;
                icmp_ln174_3_reg_458_pp0_iter2_reg <= icmp_ln174_3_reg_458_pp0_iter1_reg;
                icmp_ln174_3_reg_458_pp0_iter3_reg <= icmp_ln174_3_reg_458_pp0_iter2_reg;
                icmp_ln174_3_reg_458_pp0_iter4_reg <= icmp_ln174_3_reg_458_pp0_iter3_reg;
                icmp_ln174_3_reg_458_pp0_iter5_reg <= icmp_ln174_3_reg_458_pp0_iter4_reg;
                icmp_ln174_3_reg_458_pp0_iter6_reg <= icmp_ln174_3_reg_458_pp0_iter5_reg;
                icmp_ln174_3_reg_458_pp0_iter7_reg <= icmp_ln174_3_reg_458_pp0_iter6_reg;
                icmp_ln174_3_reg_458_pp0_iter8_reg <= icmp_ln174_3_reg_458_pp0_iter7_reg;
                icmp_ln174_3_reg_458_pp0_iter9_reg <= icmp_ln174_3_reg_458_pp0_iter8_reg;
                icmp_ln174_reg_446_pp0_iter10_reg <= icmp_ln174_reg_446_pp0_iter9_reg;
                icmp_ln174_reg_446_pp0_iter11_reg <= icmp_ln174_reg_446_pp0_iter10_reg;
                icmp_ln174_reg_446_pp0_iter12_reg <= icmp_ln174_reg_446_pp0_iter11_reg;
                icmp_ln174_reg_446_pp0_iter13_reg <= icmp_ln174_reg_446_pp0_iter12_reg;
                icmp_ln174_reg_446_pp0_iter14_reg <= icmp_ln174_reg_446_pp0_iter13_reg;
                icmp_ln174_reg_446_pp0_iter15_reg <= icmp_ln174_reg_446_pp0_iter14_reg;
                icmp_ln174_reg_446_pp0_iter16_reg <= icmp_ln174_reg_446_pp0_iter15_reg;
                icmp_ln174_reg_446_pp0_iter17_reg <= icmp_ln174_reg_446_pp0_iter16_reg;
                icmp_ln174_reg_446_pp0_iter18_reg <= icmp_ln174_reg_446_pp0_iter17_reg;
                icmp_ln174_reg_446_pp0_iter19_reg <= icmp_ln174_reg_446_pp0_iter18_reg;
                icmp_ln174_reg_446_pp0_iter20_reg <= icmp_ln174_reg_446_pp0_iter19_reg;
                icmp_ln174_reg_446_pp0_iter21_reg <= icmp_ln174_reg_446_pp0_iter20_reg;
                icmp_ln174_reg_446_pp0_iter22_reg <= icmp_ln174_reg_446_pp0_iter21_reg;
                icmp_ln174_reg_446_pp0_iter23_reg <= icmp_ln174_reg_446_pp0_iter22_reg;
                icmp_ln174_reg_446_pp0_iter24_reg <= icmp_ln174_reg_446_pp0_iter23_reg;
                icmp_ln174_reg_446_pp0_iter25_reg <= icmp_ln174_reg_446_pp0_iter24_reg;
                icmp_ln174_reg_446_pp0_iter26_reg <= icmp_ln174_reg_446_pp0_iter25_reg;
                icmp_ln174_reg_446_pp0_iter2_reg <= icmp_ln174_reg_446_pp0_iter1_reg;
                icmp_ln174_reg_446_pp0_iter3_reg <= icmp_ln174_reg_446_pp0_iter2_reg;
                icmp_ln174_reg_446_pp0_iter4_reg <= icmp_ln174_reg_446_pp0_iter3_reg;
                icmp_ln174_reg_446_pp0_iter5_reg <= icmp_ln174_reg_446_pp0_iter4_reg;
                icmp_ln174_reg_446_pp0_iter6_reg <= icmp_ln174_reg_446_pp0_iter5_reg;
                icmp_ln174_reg_446_pp0_iter7_reg <= icmp_ln174_reg_446_pp0_iter6_reg;
                icmp_ln174_reg_446_pp0_iter8_reg <= icmp_ln174_reg_446_pp0_iter7_reg;
                icmp_ln174_reg_446_pp0_iter9_reg <= icmp_ln174_reg_446_pp0_iter8_reg;
                lshr_ln5_reg_417_pp0_iter2_reg <= lshr_ln5_reg_417_pp0_iter1_reg;
                lshr_ln5_reg_417_pp0_iter3_reg <= lshr_ln5_reg_417_pp0_iter2_reg;
                mul231_1_reg_512 <= grp_fu_2310_p_dout0;
                mul231_2_reg_522 <= grp_fu_2314_p_dout0;
                mul231_3_reg_532 <= grp_fu_2318_p_dout0;
                mul3_reg_502 <= grp_fu_936_p_dout0;
                weighted_1_load_reg_517 <= weighted_1_q0;
                weighted_2_load_reg_527 <= weighted_2_q0;
                weighted_3_load_reg_537 <= weighted_3_q0;
                weighted_load_reg_507 <= weighted_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_1_load_reg_467 <= acc_1_q1;
                acc_2_load_reg_472 <= acc_2_q1;
                acc_3_load_reg_477 <= acc_3_q1;
                acc_load_reg_462 <= acc_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_1_address0 <= acc_1_addr_reg_428_pp0_iter26_reg;
    acc_1_address1 <= zext_ln176_fu_320_p1(6 - 1 downto 0);

    acc_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_1_ce0 <= ap_const_logic_1;
        else 
            acc_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_1_ce1 <= ap_const_logic_1;
        else 
            acc_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_d0 <= div235_1_reg_567;

    acc_1_we0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001, icmp_ln174_1_reg_450_pp0_iter26_reg)
    begin
        if (((icmp_ln174_1_reg_450_pp0_iter26_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_1_we0 <= ap_const_logic_1;
        else 
            acc_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_address0 <= acc_2_addr_reg_434_pp0_iter26_reg;
    acc_2_address1 <= zext_ln176_fu_320_p1(6 - 1 downto 0);

    acc_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_2_ce0 <= ap_const_logic_1;
        else 
            acc_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_2_ce1 <= ap_const_logic_1;
        else 
            acc_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_d0 <= div235_2_reg_572;

    acc_2_we0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001, icmp_ln174_2_reg_454_pp0_iter26_reg)
    begin
        if (((icmp_ln174_2_reg_454_pp0_iter26_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_2_we0 <= ap_const_logic_1;
        else 
            acc_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_address0 <= acc_3_addr_reg_440_pp0_iter26_reg;
    acc_3_address1 <= zext_ln176_fu_320_p1(6 - 1 downto 0);

    acc_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_3_ce0 <= ap_const_logic_1;
        else 
            acc_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_3_ce1 <= ap_const_logic_1;
        else 
            acc_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_d0 <= div235_3_reg_577;

    acc_3_we0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001, icmp_ln174_3_reg_458_pp0_iter26_reg)
    begin
        if (((icmp_ln174_3_reg_458_pp0_iter26_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_3_we0 <= ap_const_logic_1;
        else 
            acc_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_address0 <= acc_addr_reg_422_pp0_iter26_reg;
    acc_address1 <= zext_ln176_fu_320_p1(6 - 1 downto 0);

    acc_ce0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_ce0 <= ap_const_logic_1;
        else 
            acc_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_ce1 <= ap_const_logic_1;
        else 
            acc_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    acc_d0 <= div_reg_562;

    acc_we0_assign_proc : process(ap_enable_reg_pp0_iter27, ap_block_pp0_stage0_11001, icmp_ln174_reg_446_pp0_iter26_reg)
    begin
        if (((icmp_ln174_reg_446_pp0_iter26_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then 
            acc_we0 <= ap_const_logic_1;
        else 
            acc_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln172_fu_372_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_3) + unsigned(ap_const_lv6_4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_276_p3)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_fu_276_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter26_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter26_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27)
    begin
        if (((ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = 
    ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_72, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_x_3 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_x_3 <= x_fu_72;
        end if; 
    end process;

    grp_fu_2294_p_ce <= ap_const_logic_1;
    grp_fu_2294_p_din0 <= mul3_reg_502;
    grp_fu_2294_p_din1 <= weighted_load_reg_507;
    grp_fu_2294_p_opcode <= ap_const_lv2_0;
    grp_fu_2298_p_ce <= ap_const_logic_1;
    grp_fu_2298_p_din0 <= mul231_1_reg_512;
    grp_fu_2298_p_din1 <= weighted_1_load_reg_517;
    grp_fu_2298_p_opcode <= ap_const_lv2_0;
    grp_fu_2302_p_ce <= ap_const_logic_1;
    grp_fu_2302_p_din0 <= mul231_2_reg_522;
    grp_fu_2302_p_din1 <= weighted_2_load_reg_527;
    grp_fu_2302_p_opcode <= ap_const_lv2_0;
    grp_fu_2306_p_ce <= ap_const_logic_1;
    grp_fu_2306_p_din0 <= mul231_3_reg_532;
    grp_fu_2306_p_din1 <= weighted_3_load_reg_537;
    grp_fu_2306_p_opcode <= ap_const_lv2_0;
    grp_fu_2310_p_ce <= ap_const_logic_1;
    grp_fu_2310_p_din0 <= mul1;
    grp_fu_2310_p_din1 <= acc_1_load_reg_467;
    grp_fu_2314_p_ce <= ap_const_logic_1;
    grp_fu_2314_p_din0 <= mul1;
    grp_fu_2314_p_din1 <= acc_2_load_reg_472;
    grp_fu_2318_p_ce <= ap_const_logic_1;
    grp_fu_2318_p_din0 <= mul1;
    grp_fu_2318_p_din1 <= acc_3_load_reg_477;
    grp_fu_936_p_ce <= ap_const_logic_1;
    grp_fu_936_p_din0 <= mul1;
    grp_fu_936_p_din1 <= acc_load_reg_462;
    grp_fu_940_p_ce <= ap_const_logic_1;
    grp_fu_940_p_din0 <= add1_reg_542;
    grp_fu_940_p_din1 <= l_new;
    icmp_ln174_1_fu_334_p2 <= "1" when (signed(zext_ln172_1_fu_298_p1) < signed(d)) else "0";
    icmp_ln174_2_fu_350_p2 <= "1" when (signed(zext_ln174_fu_346_p1) < signed(d)) else "0";
    icmp_ln174_3_fu_366_p2 <= "1" when (signed(zext_ln174_1_fu_362_p1) < signed(d)) else "0";
    icmp_ln174_fu_328_p2 <= "1" when (signed(zext_ln172_fu_288_p1) < signed(d)) else "0";
    lshr_ln5_fu_302_p4 <= ap_sig_allocacmp_x_3(4 downto 2);
    or_ln172_1_fu_340_p2 <= (trunc_ln172_fu_284_p1 or ap_const_lv5_2);
    or_ln172_2_fu_356_p2 <= (trunc_ln172_fu_284_p1 or ap_const_lv5_3);
    or_ln172_fu_292_p2 <= (trunc_ln172_fu_284_p1 or ap_const_lv5_1);
    tmp_fu_276_p3 <= ap_sig_allocacmp_x_3(5 downto 5);
    tmp_s_fu_312_p3 <= (i_4 & lshr_ln5_fu_302_p4);
    trunc_ln172_fu_284_p1 <= ap_sig_allocacmp_x_3(5 - 1 downto 0);
    weighted_1_address0 <= zext_ln172_2_fu_383_p1(3 - 1 downto 0);

    weighted_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weighted_1_ce0 <= ap_const_logic_1;
        else 
            weighted_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weighted_2_address0 <= zext_ln172_2_fu_383_p1(3 - 1 downto 0);

    weighted_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weighted_2_ce0 <= ap_const_logic_1;
        else 
            weighted_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weighted_3_address0 <= zext_ln172_2_fu_383_p1(3 - 1 downto 0);

    weighted_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weighted_3_ce0 <= ap_const_logic_1;
        else 
            weighted_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weighted_address0 <= zext_ln172_2_fu_383_p1(3 - 1 downto 0);

    weighted_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weighted_ce0 <= ap_const_logic_1;
        else 
            weighted_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln172_1_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln172_fu_292_p2),32));
    zext_ln172_2_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln5_reg_417_pp0_iter3_reg),64));
    zext_ln172_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_3),32));
    zext_ln174_1_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln172_2_fu_356_p2),32));
    zext_ln174_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln172_1_fu_340_p2),32));
    zext_ln176_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_312_p3),64));
end behav;
