-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flash_attention_hls_flash_attention_hls_Pipeline_STORE_O_VITIS_LOOP_188_5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem3_AWVALID : OUT STD_LOGIC;
    m_axi_gmem3_AWREADY : IN STD_LOGIC;
    m_axi_gmem3_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_WVALID : OUT STD_LOGIC;
    m_axi_gmem3_WREADY : IN STD_LOGIC;
    m_axi_gmem3_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_WLAST : OUT STD_LOGIC;
    m_axi_gmem3_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_ARVALID : OUT STD_LOGIC;
    m_axi_gmem3_ARREADY : IN STD_LOGIC;
    m_axi_gmem3_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem3_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem3_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem3_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RVALID : IN STD_LOGIC;
    m_axi_gmem3_RREADY : OUT STD_LOGIC;
    m_axi_gmem3_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem3_RLAST : IN STD_LOGIC;
    m_axi_gmem3_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem3_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_BVALID : IN STD_LOGIC;
    m_axi_gmem3_BREADY : OUT STD_LOGIC;
    m_axi_gmem3_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem3_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem3_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    d : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln187 : IN STD_LOGIC_VECTOR (63 downto 0);
    acc_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_ce0 : OUT STD_LOGIC;
    acc_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_1_ce0 : OUT STD_LOGIC;
    acc_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_2_ce0 : OUT STD_LOGIC;
    acc_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    acc_3_ce0 : OUT STD_LOGIC;
    acc_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln63 : IN STD_LOGIC_VECTOR (30 downto 0);
    shl_ln68_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    O : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of flash_attention_hls_flash_attention_hls_Pipeline_STORE_O_VITIS_LOOP_188_5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal or_ln187_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln187_reg_522_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io : BOOLEAN;
    signal icmp_ln188_1_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln187_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem3_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem3_blk_n_W : STD_LOGIC;
    signal gmem3_blk_n_AW : STD_LOGIC;
    signal first_iter_3_reg_223 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln63_cast_fu_235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_cast_reg_513 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln187_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln187_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln187_1_fu_309_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln187_1_reg_526 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln188_fu_329_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln188_reg_531 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln188_reg_531_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln190_fu_343_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln190_reg_536 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln188_fu_349_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln188_reg_541 : STD_LOGIC_VECTOR (30 downto 0);
    signal sext_ln188_mid2_v_reg_546 : STD_LOGIC_VECTOR (61 downto 0);
    signal icmp_ln188_1_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln188_1_reg_571_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_438_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_575 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_first_iter_3_phi_fu_227_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal zext_ln190_fu_413_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln187_1_fu_428_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal x_2_fu_110 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal i_fu_114 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten44_fu_118 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln187_3_fu_274_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln188_fu_260_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln188_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln187_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln187_fu_283_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln187_fu_317_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln187_fu_301_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_s_fu_321_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal lshr_ln2_fu_333_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln187_fu_377_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln187_1_fu_381_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln188_mid2_v_v_v_v_v_fu_386_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln187_fu_394_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln187_2_fu_398_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln188_1_fu_420_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_438_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_1_fu_438_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_438_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_438_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_438_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component flash_attention_hls_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component flash_attention_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_U196 : component flash_attention_hls_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => acc_q0,
        din1 => acc_1_q0,
        din2 => acc_2_q0,
        din3 => acc_3_q0,
        def => tmp_1_fu_438_p9,
        sel => trunc_ln188_reg_531_pp0_iter2_reg,
        dout => tmp_1_fu_438_p11);

    flow_control_loop_pipe_sequential_init_U : component flash_attention_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    first_iter_3_reg_223_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln187_reg_518 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                first_iter_3_reg_223 <= ap_const_lv1_0;
            elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                first_iter_3_reg_223 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    i_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_114 <= ap_const_lv4_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln187_fu_269_p2 = ap_const_lv1_0))) then 
                    i_fu_114 <= select_ln187_1_fu_309_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten44_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten44_fu_118 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln187_fu_269_p2 = ap_const_lv1_0))) then 
                    indvar_flatten44_fu_118 <= add_ln187_3_fu_274_p2;
                end if;
            end if; 
        end if;
    end process;

    x_2_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_2_fu_110 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln187_fu_269_p2 = ap_const_lv1_0))) then 
                    x_2_fu_110 <= add_ln188_fu_349_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln188_reg_541 <= add_ln188_fu_349_p2;
                add_ln190_reg_536 <= add_ln190_fu_343_p2;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln187_reg_518 <= icmp_ln187_fu_269_p2;
                or_ln187_reg_522 <= or_ln187_fu_295_p2;
                select_ln187_1_reg_526 <= select_ln187_1_fu_309_p3;
                trunc_ln188_reg_531 <= trunc_ln188_fu_329_p1;
                    zext_ln63_cast_reg_513(30 downto 0) <= zext_ln63_cast_fu_235_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                icmp_ln188_1_reg_571 <= icmp_ln188_1_fu_423_p2;
                icmp_ln188_1_reg_571_pp0_iter3_reg <= icmp_ln188_1_reg_571;
                icmp_ln188_1_reg_571_pp0_iter4_reg <= icmp_ln188_1_reg_571_pp0_iter3_reg;
                icmp_ln188_1_reg_571_pp0_iter5_reg <= icmp_ln188_1_reg_571_pp0_iter4_reg;
                icmp_ln188_1_reg_571_pp0_iter6_reg <= icmp_ln188_1_reg_571_pp0_iter5_reg;
                icmp_ln188_1_reg_571_pp0_iter7_reg <= icmp_ln188_1_reg_571_pp0_iter6_reg;
                icmp_ln188_1_reg_571_pp0_iter8_reg <= icmp_ln188_1_reg_571_pp0_iter7_reg;
                or_ln187_reg_522_pp0_iter2_reg <= or_ln187_reg_522;
                sext_ln188_mid2_v_reg_546 <= add_ln187_2_fu_398_p2(63 downto 2);
                tmp_1_reg_575 <= tmp_1_fu_438_p11;
                trunc_ln188_reg_531_pp0_iter2_reg <= trunc_ln188_reg_531;
            end if;
        end if;
    end process;
    zext_ln63_cast_reg_513(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_1_address0 <= zext_ln190_fu_413_p1(6 - 1 downto 0);

    acc_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_1_ce0 <= ap_const_logic_1;
        else 
            acc_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_address0 <= zext_ln190_fu_413_p1(6 - 1 downto 0);

    acc_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_2_ce0 <= ap_const_logic_1;
        else 
            acc_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_address0 <= zext_ln190_fu_413_p1(6 - 1 downto 0);

    acc_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_3_ce0 <= ap_const_logic_1;
        else 
            acc_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    acc_address0 <= zext_ln190_fu_413_p1(6 - 1 downto 0);

    acc_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            acc_ce0 <= ap_const_logic_1;
        else 
            acc_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln187_1_fu_381_p2 <= std_logic_vector(unsigned(zext_ln187_fu_377_p1) + unsigned(shl_ln68_2));
    add_ln187_2_fu_398_p2 <= std_logic_vector(signed(sext_ln187_fu_394_p1) + signed(O));
    add_ln187_3_fu_274_p2 <= std_logic_vector(unsigned(indvar_flatten44_fu_118) + unsigned(ap_const_lv64_1));
    add_ln187_fu_283_p2 <= std_logic_vector(unsigned(i_fu_114) + unsigned(ap_const_lv4_1));
    add_ln188_fu_349_p2 <= std_logic_vector(unsigned(select_ln187_fu_301_p3) + unsigned(ap_const_lv31_1));
    add_ln190_fu_343_p2 <= std_logic_vector(unsigned(tmp_s_fu_321_p3) + unsigned(lshr_ln2_fu_333_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter9, m_axi_gmem3_WREADY, ap_block_state4_io, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((m_axi_gmem3_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter9, m_axi_gmem3_WREADY, ap_block_state4_io, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((m_axi_gmem3_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmem3_BVALID, icmp_ln188_1_reg_571_pp0_iter8_reg)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((icmp_ln188_1_reg_571_pp0_iter8_reg = ap_const_lv1_0) and (m_axi_gmem3_BVALID = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem3_AWREADY, or_ln187_reg_522_pp0_iter2_reg)
    begin
                ap_block_state4_io <= ((m_axi_gmem3_AWREADY = ap_const_logic_0) and (or_ln187_reg_522_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln187_fu_269_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln187_fu_269_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_first_iter_3_phi_fu_227_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, first_iter_3_reg_223, icmp_ln187_reg_518)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln187_reg_518 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_first_iter_3_phi_fu_227_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_first_iter_3_phi_fu_227_p4 <= first_iter_3_reg_223;
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    gmem3_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem3_AWREADY, or_ln187_reg_522_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (or_ln187_reg_522_pp0_iter2_reg = ap_const_lv1_1))) then 
            gmem3_blk_n_AW <= m_axi_gmem3_AWREADY;
        else 
            gmem3_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem3_BVALID, icmp_ln188_1_reg_571_pp0_iter8_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln188_1_reg_571_pp0_iter8_reg = ap_const_lv1_0))) then 
            gmem3_blk_n_B <= m_axi_gmem3_BVALID;
        else 
            gmem3_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem3_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem3_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem3_blk_n_W <= m_axi_gmem3_WREADY;
        else 
            gmem3_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln187_fu_269_p2 <= "1" when (indvar_flatten44_fu_118 = mul_ln187) else "0";
    icmp_ln188_1_fu_423_p2 <= "1" when (signed(zext_ln188_1_fu_420_p1) < signed(d)) else "0";
    icmp_ln188_fu_264_p2 <= "1" when (signed(zext_ln188_fu_260_p1) < signed(d)) else "0";
    lshr_ln2_fu_333_p4 <= select_ln187_fu_301_p3(7 downto 2);
    m_axi_gmem3_ARADDR <= ap_const_lv64_0;
    m_axi_gmem3_ARBURST <= ap_const_lv2_0;
    m_axi_gmem3_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem3_ARID <= ap_const_lv1_0;
    m_axi_gmem3_ARLEN <= ap_const_lv32_0;
    m_axi_gmem3_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem3_ARPROT <= ap_const_lv3_0;
    m_axi_gmem3_ARQOS <= ap_const_lv4_0;
    m_axi_gmem3_ARREGION <= ap_const_lv4_0;
    m_axi_gmem3_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem3_ARUSER <= ap_const_lv1_0;
    m_axi_gmem3_ARVALID <= ap_const_logic_0;
    m_axi_gmem3_AWADDR <= sext_ln187_1_fu_428_p1;
    m_axi_gmem3_AWBURST <= ap_const_lv2_0;
    m_axi_gmem3_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem3_AWID <= ap_const_lv1_0;
    m_axi_gmem3_AWLEN <= zext_ln63_cast_reg_513;
    m_axi_gmem3_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem3_AWPROT <= ap_const_lv3_0;
    m_axi_gmem3_AWQOS <= ap_const_lv4_0;
    m_axi_gmem3_AWREGION <= ap_const_lv4_0;
    m_axi_gmem3_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem3_AWUSER <= ap_const_lv1_0;

    m_axi_gmem3_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter3, or_ln187_reg_522_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (or_ln187_reg_522_pp0_iter2_reg = ap_const_lv1_1))) then 
            m_axi_gmem3_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem3_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem3_BREADY_assign_proc : process(ap_enable_reg_pp0_iter9, icmp_ln188_1_reg_571_pp0_iter8_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln188_1_reg_571_pp0_iter8_reg = ap_const_lv1_0))) then 
            m_axi_gmem3_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem3_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem3_RREADY <= ap_const_logic_0;
    m_axi_gmem3_WDATA <= tmp_1_reg_575;
    m_axi_gmem3_WID <= ap_const_lv1_0;
    m_axi_gmem3_WLAST <= ap_const_logic_0;
    m_axi_gmem3_WSTRB <= ap_const_lv4_F;
    m_axi_gmem3_WUSER <= ap_const_lv1_0;

    m_axi_gmem3_WVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem3_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem3_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln187_fu_295_p2 <= (xor_ln187_fu_289_p2 or ap_phi_mux_first_iter_3_phi_fu_227_p4);
    select_ln187_1_fu_309_p3 <= 
        i_fu_114 when (icmp_ln188_fu_264_p2(0) = '1') else 
        add_ln187_fu_283_p2;
    select_ln187_fu_301_p3 <= 
        x_2_fu_110 when (icmp_ln188_fu_264_p2(0) = '1') else 
        ap_const_lv31_0;
        sext_ln187_1_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln188_mid2_v_reg_546),64));

        sext_ln187_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln188_mid2_v_v_v_v_v_fu_386_p3),64));

    sext_ln188_mid2_v_v_v_v_v_fu_386_p3 <= (add_ln187_1_fu_381_p2 & ap_const_lv2_0);
    sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3 <= (select_ln187_1_reg_526 & ap_const_lv5_0);
    tmp_1_fu_438_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_321_p3 <= (trunc_ln187_fu_317_p1 & ap_const_lv3_0);
    trunc_ln187_fu_317_p1 <= select_ln187_1_fu_309_p3(3 - 1 downto 0);
    trunc_ln188_fu_329_p1 <= select_ln187_fu_301_p3(2 - 1 downto 0);
    xor_ln187_fu_289_p2 <= (icmp_ln188_fu_264_p2 xor ap_const_lv1_1);
    zext_ln187_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln188_mid2_v_v_v_v_v_v_v_v_v_fu_370_p3),32));
    zext_ln188_1_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln188_reg_541),32));
    zext_ln188_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_2_fu_110),32));
    zext_ln190_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln190_reg_536),64));
    zext_ln63_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln63),32));
end behav;
