// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_VITIS_LOOP_80_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d,
        zext_ln82,
        acc_address0,
        acc_ce0,
        acc_we0,
        acc_d0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_we0,
        acc_1_d0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_we0,
        acc_2_d0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_we0,
        acc_3_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] d;
input  [5:0] zext_ln82;
output  [5:0] acc_address0;
output   acc_ce0;
output   acc_we0;
output  [31:0] acc_d0;
output  [5:0] acc_1_address0;
output   acc_1_ce0;
output   acc_1_we0;
output  [31:0] acc_1_d0;
output  [5:0] acc_2_address0;
output   acc_2_ce0;
output   acc_2_we0;
output  [31:0] acc_2_d0;
output  [5:0] acc_3_address0;
output   acc_3_ce0;
output   acc_3_we0;
output  [31:0] acc_3_d0;

reg ap_idle;
reg acc_ce0;
reg acc_we0;
reg acc_1_ce0;
reg acc_1_we0;
reg acc_2_ce0;
reg acc_2_we0;
reg acc_3_ce0;
reg acc_3_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln80_fu_132_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln82_1_fu_164_p1;
reg   [30:0] x_fu_48;
wire   [30:0] add_ln80_fu_138_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_x_1;
wire   [1:0] trunc_ln80_fu_144_p1;
wire   [31:0] zext_ln80_fu_128_p1;
wire   [5:0] lshr_ln1_fu_148_p4;
wire   [5:0] add_ln82_fu_158_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 x_fu_48 = 31'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln80_fu_132_p2 == 1'd1)) begin
            x_fu_48 <= add_ln80_fu_138_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_48 <= 31'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_ce0 = 1'b1;
    end else begin
        acc_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln80_fu_144_p1 == 2'd1) & (icmp_ln80_fu_132_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_we0 = 1'b1;
    end else begin
        acc_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_ce0 = 1'b1;
    end else begin
        acc_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln80_fu_144_p1 == 2'd2) & (icmp_ln80_fu_132_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_we0 = 1'b1;
    end else begin
        acc_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_ce0 = 1'b1;
    end else begin
        acc_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln80_fu_144_p1 == 2'd3) & (icmp_ln80_fu_132_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_we0 = 1'b1;
    end else begin
        acc_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_ce0 = 1'b1;
    end else begin
        acc_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln80_fu_144_p1 == 2'd0) & (icmp_ln80_fu_132_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_we0 = 1'b1;
    end else begin
        acc_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_fu_132_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_x_1 = 31'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_48;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_address0 = zext_ln82_1_fu_164_p1;

assign acc_1_d0 = 32'd0;

assign acc_2_address0 = zext_ln82_1_fu_164_p1;

assign acc_2_d0 = 32'd0;

assign acc_3_address0 = zext_ln82_1_fu_164_p1;

assign acc_3_d0 = 32'd0;

assign acc_address0 = zext_ln82_1_fu_164_p1;

assign acc_d0 = 32'd0;

assign add_ln80_fu_138_p2 = (ap_sig_allocacmp_x_1 + 31'd1);

assign add_ln82_fu_158_p2 = (zext_ln82 + lshr_ln1_fu_148_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln80_fu_132_p2 = (($signed(zext_ln80_fu_128_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_148_p4 = {{ap_sig_allocacmp_x_1[7:2]}};

assign trunc_ln80_fu_144_p1 = ap_sig_allocacmp_x_1[1:0];

assign zext_ln80_fu_128_p1 = ap_sig_allocacmp_x_1;

assign zext_ln82_1_fu_164_p1 = add_ln82_fu_158_p2;

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_VITIS_LOOP_80_2
