// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module flash_attention_hls_flash_attention_hls_Pipeline_LOAD_Q_VITIS_LOOP_69_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        d,
        mul_ln68,
        Qbuf_address0,
        Qbuf_ce0,
        Qbuf_we0,
        Qbuf_d0,
        Qbuf_1_address0,
        Qbuf_1_ce0,
        Qbuf_1_we0,
        Qbuf_1_d0,
        Qbuf_2_address0,
        Qbuf_2_ce0,
        Qbuf_2_we0,
        Qbuf_2_d0,
        Qbuf_3_address0,
        Qbuf_3_ce0,
        Qbuf_3_we0,
        Qbuf_3_d0,
        zext_ln63,
        shl_ln68_2,
        Q
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [31:0] d;
input  [62:0] mul_ln68;
output  [5:0] Qbuf_address0;
output   Qbuf_ce0;
output   Qbuf_we0;
output  [31:0] Qbuf_d0;
output  [5:0] Qbuf_1_address0;
output   Qbuf_1_ce0;
output   Qbuf_1_we0;
output  [31:0] Qbuf_1_d0;
output  [5:0] Qbuf_2_address0;
output   Qbuf_2_ce0;
output   Qbuf_2_we0;
output  [31:0] Qbuf_2_d0;
output  [5:0] Qbuf_3_address0;
output   Qbuf_3_ce0;
output   Qbuf_3_we0;
output  [31:0] Qbuf_3_d0;
input  [30:0] zext_ln63;
input  [31:0] shl_ln68_2;
input  [63:0] Q;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg Qbuf_ce0;
reg Qbuf_we0;
reg Qbuf_1_ce0;
reg Qbuf_1_we0;
reg Qbuf_2_ce0;
reg Qbuf_2_we0;
reg Qbuf_3_ce0;
reg Qbuf_3_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
reg   [0:0] or_ln68_reg_469;
reg   [0:0] or_ln68_reg_469_pp0_iter2_reg;
reg    ap_block_state4_io;
reg    ap_block_state12_pp0_stage0_iter11;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln68_fu_251_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_AR;
reg   [0:0] first_iter_0_reg_205;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] zext_ln63_cast_fu_217_p1;
reg   [31:0] zext_ln63_cast_reg_460;
reg   [0:0] icmp_ln68_reg_465;
wire   [0:0] or_ln68_fu_277_p2;
wire   [26:0] trunc_ln68_1_fu_303_p1;
reg   [26:0] trunc_ln68_1_reg_473;
wire   [1:0] trunc_ln69_fu_315_p1;
reg   [1:0] trunc_ln69_reg_478;
reg   [1:0] trunc_ln69_reg_478_pp0_iter2_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter3_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter4_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter5_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter6_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter7_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter8_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter9_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter10_reg;
reg   [1:0] trunc_ln69_reg_478_pp0_iter11_reg;
wire   [5:0] add_ln71_fu_329_p2;
reg   [5:0] add_ln71_reg_482;
reg   [5:0] add_ln71_reg_482_pp0_iter2_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter3_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter4_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter5_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter6_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter7_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter8_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter9_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter10_reg;
reg   [5:0] add_ln71_reg_482_pp0_iter11_reg;
reg   [63:0] gmem0_addr_reg_487;
reg   [31:0] gmem0_addr_read_reg_493;
reg   [0:0] ap_phi_mux_first_iter_0_phi_fu_209_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln71_fu_405_p1;
wire  signed [63:0] sext_ln69_fu_395_p1;
reg   [30:0] x_fu_100;
wire   [30:0] add_ln69_fu_335_p2;
reg   [30:0] i_fu_104;
wire   [30:0] select_ln68_1_fu_291_p3;
reg   [62:0] indvar_flatten_fu_108;
wire   [62:0] add_ln68_3_fu_256_p2;
wire   [31:0] bitcast_ln71_fu_412_p1;
wire   [31:0] zext_ln69_fu_242_p1;
wire   [0:0] icmp_ln69_fu_246_p2;
wire   [0:0] xor_ln68_fu_271_p2;
wire   [30:0] add_ln68_2_fu_265_p2;
wire   [2:0] trunc_ln68_fu_299_p1;
wire   [30:0] select_ln68_fu_283_p3;
wire   [5:0] tmp_s_fu_307_p3;
wire   [5:0] lshr_ln_fu_319_p4;
wire   [31:0] shl_ln_fu_356_p3;
wire   [31:0] add_ln68_fu_363_p2;
wire   [33:0] shl_ln68_1_fu_368_p3;
wire  signed [63:0] sext_ln68_fu_376_p1;
wire   [63:0] add_ln68_1_fu_380_p2;
wire   [61:0] trunc_ln2_fu_385_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 x_fu_100 = 31'd0;
#0 i_fu_104 = 31'd0;
#0 indvar_flatten_fu_108 = 63'd0;
#0 ap_done_reg = 1'b0;
end

flash_attention_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_reg_465 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        first_iter_0_reg_205 <= 1'd0;
    end else if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        first_iter_0_reg_205 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_104 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln68_fu_251_p2 == 1'd0))) begin
            i_fu_104 <= select_ln68_1_fu_291_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_108 <= 63'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln68_fu_251_p2 == 1'd0))) begin
            indvar_flatten_fu_108 <= add_ln68_3_fu_256_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_fu_100 <= 31'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln68_fu_251_p2 == 1'd0))) begin
            x_fu_100 <= add_ln69_fu_335_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln71_reg_482 <= add_ln71_fu_329_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln68_reg_465 <= icmp_ln68_fu_251_p2;
        or_ln68_reg_469 <= or_ln68_fu_277_p2;
        trunc_ln68_1_reg_473 <= trunc_ln68_1_fu_303_p1;
        trunc_ln69_reg_478 <= trunc_ln69_fu_315_p1;
        zext_ln63_cast_reg_460[30 : 0] <= zext_ln63_cast_fu_217_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln71_reg_482_pp0_iter10_reg <= add_ln71_reg_482_pp0_iter9_reg;
        add_ln71_reg_482_pp0_iter11_reg <= add_ln71_reg_482_pp0_iter10_reg;
        add_ln71_reg_482_pp0_iter2_reg <= add_ln71_reg_482;
        add_ln71_reg_482_pp0_iter3_reg <= add_ln71_reg_482_pp0_iter2_reg;
        add_ln71_reg_482_pp0_iter4_reg <= add_ln71_reg_482_pp0_iter3_reg;
        add_ln71_reg_482_pp0_iter5_reg <= add_ln71_reg_482_pp0_iter4_reg;
        add_ln71_reg_482_pp0_iter6_reg <= add_ln71_reg_482_pp0_iter5_reg;
        add_ln71_reg_482_pp0_iter7_reg <= add_ln71_reg_482_pp0_iter6_reg;
        add_ln71_reg_482_pp0_iter8_reg <= add_ln71_reg_482_pp0_iter7_reg;
        add_ln71_reg_482_pp0_iter9_reg <= add_ln71_reg_482_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem0_addr_read_reg_493 <= m_axi_gmem0_RDATA;
        gmem0_addr_reg_487 <= sext_ln69_fu_395_p1;
        or_ln68_reg_469_pp0_iter2_reg <= or_ln68_reg_469;
        trunc_ln69_reg_478_pp0_iter10_reg <= trunc_ln69_reg_478_pp0_iter9_reg;
        trunc_ln69_reg_478_pp0_iter11_reg <= trunc_ln69_reg_478_pp0_iter10_reg;
        trunc_ln69_reg_478_pp0_iter2_reg <= trunc_ln69_reg_478;
        trunc_ln69_reg_478_pp0_iter3_reg <= trunc_ln69_reg_478_pp0_iter2_reg;
        trunc_ln69_reg_478_pp0_iter4_reg <= trunc_ln69_reg_478_pp0_iter3_reg;
        trunc_ln69_reg_478_pp0_iter5_reg <= trunc_ln69_reg_478_pp0_iter4_reg;
        trunc_ln69_reg_478_pp0_iter6_reg <= trunc_ln69_reg_478_pp0_iter5_reg;
        trunc_ln69_reg_478_pp0_iter7_reg <= trunc_ln69_reg_478_pp0_iter6_reg;
        trunc_ln69_reg_478_pp0_iter8_reg <= trunc_ln69_reg_478_pp0_iter7_reg;
        trunc_ln69_reg_478_pp0_iter9_reg <= trunc_ln69_reg_478_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_1_ce0 = 1'b1;
    end else begin
        Qbuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln69_reg_478_pp0_iter11_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_1_we0 = 1'b1;
    end else begin
        Qbuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_2_ce0 = 1'b1;
    end else begin
        Qbuf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln69_reg_478_pp0_iter11_reg == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_2_we0 = 1'b1;
    end else begin
        Qbuf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_3_ce0 = 1'b1;
    end else begin
        Qbuf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln69_reg_478_pp0_iter11_reg == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_3_we0 = 1'b1;
    end else begin
        Qbuf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_ce0 = 1'b1;
    end else begin
        Qbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln69_reg_478_pp0_iter11_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Qbuf_we0 = 1'b1;
    end else begin
        Qbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln68_fu_251_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_reg_465 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_first_iter_0_phi_fu_209_p4 = 1'd0;
    end else begin
        ap_phi_mux_first_iter_0_phi_fu_209_p4 = first_iter_0_reg_205;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (or_ln68_reg_469_pp0_iter2_reg == 1'd1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (or_ln68_reg_469_pp0_iter2_reg == 1'd1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Qbuf_1_address0 = zext_ln71_fu_405_p1;

assign Qbuf_1_d0 = bitcast_ln71_fu_412_p1;

assign Qbuf_2_address0 = zext_ln71_fu_405_p1;

assign Qbuf_2_d0 = bitcast_ln71_fu_412_p1;

assign Qbuf_3_address0 = zext_ln71_fu_405_p1;

assign Qbuf_3_d0 = bitcast_ln71_fu_412_p1;

assign Qbuf_address0 = zext_ln71_fu_405_p1;

assign Qbuf_d0 = bitcast_ln71_fu_412_p1;

assign add_ln68_1_fu_380_p2 = ($signed(sext_ln68_fu_376_p1) + $signed(Q));

assign add_ln68_2_fu_265_p2 = (i_fu_104 + 31'd1);

assign add_ln68_3_fu_256_p2 = (indvar_flatten_fu_108 + 63'd1);

assign add_ln68_fu_363_p2 = (shl_ln_fu_356_p3 + shl_ln68_2);

assign add_ln69_fu_335_p2 = (select_ln68_fu_283_p3 + 31'd1);

assign add_ln71_fu_329_p2 = (tmp_s_fu_307_p3 + lshr_ln_fu_319_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage0_iter11)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state12_pp0_stage0_iter11 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem0_ARREADY == 1'b0) & (or_ln68_reg_469_pp0_iter2_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign bitcast_ln71_fu_412_p1 = gmem0_addr_read_reg_493;

assign icmp_ln68_fu_251_p2 = ((indvar_flatten_fu_108 == mul_ln68) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_246_p2 = (($signed(zext_ln69_fu_242_p1) < $signed(d)) ? 1'b1 : 1'b0);

assign lshr_ln_fu_319_p4 = {{select_ln68_fu_283_p3[7:2]}};

assign m_axi_gmem0_ARADDR = gmem0_addr_reg_487;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = zext_ln63_cast_reg_460;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign or_ln68_fu_277_p2 = (xor_ln68_fu_271_p2 | ap_phi_mux_first_iter_0_phi_fu_209_p4);

assign select_ln68_1_fu_291_p3 = ((icmp_ln69_fu_246_p2[0:0] == 1'b1) ? i_fu_104 : add_ln68_2_fu_265_p2);

assign select_ln68_fu_283_p3 = ((icmp_ln69_fu_246_p2[0:0] == 1'b1) ? x_fu_100 : 31'd0);

assign sext_ln68_fu_376_p1 = $signed(shl_ln68_1_fu_368_p3);

assign sext_ln69_fu_395_p1 = $signed(trunc_ln2_fu_385_p4);

assign shl_ln68_1_fu_368_p3 = {{add_ln68_fu_363_p2}, {2'd0}};

assign shl_ln_fu_356_p3 = {{trunc_ln68_1_reg_473}, {5'd0}};

assign tmp_s_fu_307_p3 = {{trunc_ln68_fu_299_p1}, {3'd0}};

assign trunc_ln2_fu_385_p4 = {{add_ln68_1_fu_380_p2[63:2]}};

assign trunc_ln68_1_fu_303_p1 = select_ln68_1_fu_291_p3[26:0];

assign trunc_ln68_fu_299_p1 = select_ln68_1_fu_291_p3[2:0];

assign trunc_ln69_fu_315_p1 = select_ln68_fu_283_p3[1:0];

assign xor_ln68_fu_271_p2 = (icmp_ln69_fu_246_p2 ^ 1'd1);

assign zext_ln63_cast_fu_217_p1 = zext_ln63;

assign zext_ln69_fu_242_p1 = x_fu_100;

assign zext_ln71_fu_405_p1 = add_ln71_reg_482_pp0_iter11_reg;

always @ (posedge ap_clk) begin
    zext_ln63_cast_reg_460[31] <= 1'b0;
end

endmodule //flash_attention_hls_flash_attention_hls_Pipeline_LOAD_Q_VITIS_LOOP_69_1
